import type { Idioma } from "@/lib/ui/idioma";

/**
 * User-visible copy. English is the default and the fallback.
 * Add a key here and in `es` together; `lib/ui/diccionario.test.ts` checks they match.
 */
export const en = {
  idioma: {
    grupo: "Language",
    en: "EN",
    es: "ES",
  },
  nav: {
    events: "Events",
    tasks: "Tasks",
    account: "Account",
    main: "Main",
    back: "Back",
  },
  tema: {
    light: "Switch to light theme",
    dark: "Switch to dark theme",
  },
  comunes: {
    loading: "Loading…",
    tryAgain: "Try again",
    sample: "Sample",
    event: "Event",
    all: "All",
    amount: "Amount",
    date: "Date",
    unassigned: "Unassigned",
    done: "Done",
    now: "Now",
    later: "Later",
  },
  eventos: {
    title: "Events",
    create: "+ Create",
    joinCode: "Join with code",
    noLoad: "Could not load events.",
    empty: "No events yet.",
    emptyHelp: "Create one or join with a code.",
    member: "Member",
    organizer: "Organizer",
    team: "Team",
    volunteer: "Volunteer",
    toReview: "{n} to review",
    inReview: "{n} in review",
    invite: "Invite",
    inviteRegion: "Invite",
    createCode: "Create a code",
    email: "Email",
    inviteEmail: "Invite by email",
    copyLink: "Copy link",
    copied: "Copied",
    inviteFail: "Could not create the invite.",
    tablist: "Event",
    inbox: "Inbox",
    tasks: "Tasks",
    report: "Report",
    noTasks: "No tasks yet.",
    assignedLater: "When the organizer assigns you a task, it shows up here.",
    joinTitle: "Join with code",
    code: "Code",
    join: "Join",
    joinInvalid: "That code is not valid.",
    assign: "Assign",
    assignFail: "Could not assign that task.",
    createTitle: "Create event",
    newEvent: "New event",
    name: "Name",
    taskN: "Task {n}",
    titleLabel: "Title",
    type: "Type",
    amount: "Amount (USDC)",
    photoMust: "Photo must show",
    assignee: "Assign to",
    remove: "Remove {name}",
    taskWord: "task",
    addTask: "Add task",
    budget: "Budget",
    workTasks: "Work tasks",
    reimbursements: "Reimbursements",
    total: "Total",
    createEvent: "Create event",
    needFields: "Enter a name and at least one task with an amount.",
    createFail: "Could not create the event.",
    demoCreate: "Demo mode cannot create events. Sign in with your email to create one.",
    reportLead: "Budget compared with what has been paid. Each task is one payment.",
    print: "Print",
    against: "Budget against spend",
    paidLine: "Paid {paid} · Remaining {pending} · {n} volunteer",
    paidLineMany: "Paid {paid} · Remaining {pending} · {n} volunteers",
    detail: "Detail",
    limit: "Limit {amount}",
    upTo: "Up to {amount}",
    credential: "Credential",
    sampleReport: "Sample report, until live tasks load. A paid task can include a blockchain link.",
    accountsTitle: "Accounts & wallet",
    accountsLead: "One organizer and three volunteers. Each person confirms the code we email them. Then their account can receive the event payment.",
    accountDetails: "Account details",
    notSetUp: "Not set up yet",
    readyReceive: "Ready to receive payment",
    notReadyReceive: "Not ready to receive payment",
    confirm: "Confirm",
    preparing: "Preparing…",
    prepareAccounts: "Prepare accounts",
    accountsReady: "Accounts ready",
    prepareFail: "Could not prepare the account.",
    codeLabel: "Code",
    codeFor: "Code for {name}",
    limitUsdc: "Limit (USDC)",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    saveFail: "Could not save that task.",
    editOnly: "Only the organizer can edit tasks.",
    editPhoto: "This task already has a photo, so it can't be edited.",
    editPaid: "This task already has a payment, so it can't be edited.",
    editLocked: "The amount is already locked in the payment, so this task can't be edited.",
    needTitle: "Enter a title.",
    titleLong: "Title is too long.",
    needPhoto: "Enter what the photo must show.",
    noteLong: "That note is too long.",
    noCap: "Work tasks don't have a cap.",
    choosePerson: "Choose a person in this event.",
    nothingSave: "Nothing to save.",
    notInEvent: "That person is not in this event.",
  },
  bienvenida: {
    kicker: "Welcome",
    title: "You're in.",
    body: "Hyto is a marketplace of small tasks. Do the work, send a photo, and get paid in digital dollars (USDC).",
    step: "Take your first step",
  },
  landing: {
    esloganAntes: "Prove your worth.",
    esloganAcento: "Get paid.",
    sub: "Do tasks for real projects, send a photo, get paid in USDC.",
    legal: "Sign-in by Cavos · your Stellar wallet is created for you.",
    panel: "How Hyto works",
    panelQ: "Lock the budget. Review the photo. Pay the milestone.",
    panelS: "Organizers review and approve from one inbox. Mile, the AI reviewer, reads each photo; people decide every payment.",
    voluntarios: "Volunteers",
    organizadores: "Organizers",
    escrow: "Paid via Stellar escrow",
  },
  entrar: {
    signIn: "Sign in",
    signUp: "Sign up",
    newHere: "New to Hyto",
    welcomeBack: "Welcome back",
    signUpBody:
      "First time here. We'll create your Hyto account and a Stellar testnet wallet, fund it with Friendbot if the account is missing, and get it ready to hold USDC.",
    signInBody:
      "You already have an account and a wallet. Google opens that session. We won't create a new account or set up Stellar again.",
    signedIn: "Signed in",
    accountDetails: "Account details",
    dialog: "Sign in",
    dialogSignUp: "Sign up",
    title: "Sign in to Hyto",
    titleSignUp: "Sign up for Hyto",
    close: "Close",
    intro: "Google only. We won't fund Friendbot, add a trustline, or create another wallet.",
    introSignUp: "Google creates your account and sets up Stellar testnet. Email works too.",
    googleSignUp: "Sign up with Google",
    emailSignUp: "Sign up with email",
    back: "Back",
    createAccount: "Create account",
    creatingAccount: "Creating account…",
    settingUp: "Setting up your Stellar testnet wallet…",
    altaPendiente: "Open Events and tap Get ready to be paid to finish setup on Stellar testnet.",
    openEvents: "Open Events",
    emailCode: "We'll email you a code. You don't need a separate app.",
    email: "Email",
    sending: "Sending…",
    sendCode: "Send code",
    or: "or",
    openingGoogle: "Opening Google…",
    google: "Sign in with Google",
    code: "Code",
    signingIn: "Signing in…",
    resend: "Resend code",
    tryDemo: "Try demo mode",
    noAccount: "No account needed",
    demoRole: "Demo session role",
    organizerDemo: "Organizer demo account",
    volunteerDemo: "Volunteer demo account",
    enterDemo: "Enter as demo",
    legal: "Cavos on Stellar testnet. Sign in opens the wallet you already have.",
    legalSignUp:
      "Cavos on Stellar testnet. Sign up creates the wallet, uses Friendbot if the account is missing, and adds the USDC trustline.",
    switching: "Switching…",
    switchVolunteer: "Switch to the volunteer demo account",
    switchOrganizer: "Switch to the organizer demo account",
    leaving: "Leaving…",
    leaveDemo: "Leave demo",
    demoMode: "Demo mode",
    signInAgain: "Sign in again",
    espera: "Wait {n} s before requesting another code",
    couldNotSignIn: "Could not sign in.",
    leaveDemoFail: "Could not leave demo mode.",
    demoOpenFail: "Could not open the demo. Try again.",
  },
  tareas: {
    title: "My tasks",
    earned: "Earned",
    inReview: "In review",
    toDo: "To do",
    one: "task",
    many: "tasks",
    loading: "Loading tasks…",
    emptyTitle: "No tasks yet.",
    emptyBody: "Join an event with a code.",
    join: "Join with code",
    filter: "Filter tasks",
    sort: "Sort tasks",
    sortLabel: "Sort",
    sortDefault: "Default",
    sortHighest: "Highest pay",
    bestPaid: "Best paid",
    openCamera: "Open camera",
    view: "View task",
  },
  evidencia: {
    back: "Back to My tasks",
    sentAction: "Evidence sent, action needed",
    sent: "Evidence sent",
    upload: "Upload evidence",
    receiptHelp: "Upload the receipt or invoice as a PDF or an image. The organizer checks it and sends the payment.",
    photoHelp: "Photograph the finished work with the camera. The organizer checks it and sends the payment.",
    fileSent: "File sent",
    photoSent: "Photo sent",
    fixSuffix: " The organizer can't send the payment until this is fixed.",
    organizerNow: "The organizer can review it now. This task shows Paid after they send the money.",
    organizerApproves: "The organizer approves, then the payment leaves the escrow.",
    organizerCall: "Your organizer makes the final call",
    anotherMaybe: "If the photo isn't clear, the organizer may ask for another one.",
    invoicePdf: "Invoice PDF",
    alt: "Evidence",
    camera: "Camera preview",
    receiptPlaceholder: "PDF or image of the receipt",
    workPlaceholder: "Photo of the work",
    choosePdf: "Choose a PDF or image",
    gallery: "Take the photo now. Photos from the gallery are not accepted.",
    mustShow: "Your photo must show",
    takePhoto: "Take photo",
    send: "Send",
    sending: "Sending…",
    chooseFile: "Choose a file",
    openCamera: "Open camera",
    sendingNote: "Sending the photo. The recommendation can take a few seconds.",
    chooseAnother: "Choose another file",
    takeAnother: "Take another",
    sendAnother: "Send another file",
    sample: "Sample task, until your own tasks load.",
    noCameraShow: "Could not show the camera.",
    noCamera: "Could not open the camera. Allow the camera and try again.",
    cameraNotReady: "The camera is not ready yet.",
    noPhoto: "Could not take the photo.",
    badFile: "Choose a PDF, JPEG, PNG, or WebP file.",
    useCamera: "Take the photo with the camera.",
    noSend: "Could not send. Try again.",
    noTask: "We couldn't find that task.",
  },
  bandeja: {
    inbox: "Inbox",
    none: "No submissions yet.",
    oneWaiting: "{n} submission waiting for your review",
    manyWaiting: "{n} submissions waiting for your review",
    backExample: "Back to the ZEEK example",
    filter: "Filter submissions",
    nothingApprove: "Nothing to approve",
    whenPhoto: "When someone sends a photo, it shows up here.",
    invite: "Invite",
    create: "Create event",
    nothingView: "Nothing in this view.",
    assign: "Assign",
    review: "Review",
    recommendation: "Recommendation",
    noRecommendation: "No recommendation yet",
    photoMust: "Photo must show",
    mileSuggests: "Mile only suggests. You approve every payment.",
    openReview: "Open review",
    sample: "Sample event, until live tasks load.",
    updated: "Updated just now",
    retry: "Retry review",
    retrying: "Retrying…",
    retryFail: "The review could not be retried.",
  },
  numeros: {
    budget: "Budget",
    paid: "Paid",
    pending: "Remaining",
  },
  revision: {
    crumb: "Evidence review",
    openInvoice: "Open the invoice",
    sampleEvidence: "Sample evidence",
    noPhoto: "No photo yet",
    waitingVolunteer: "Waiting for the volunteer to send one.",
    steps: "Payment steps",
    sampleReview: "Sample review. The paid mark here stays on this device.",
    mileNo: "Mile is unavailable. No AI score for this photo.",
    amountReceipt: "Amount on the receipt",
    amountToPay: "Amount to pay",
    upTo: "Up to {monto}. Confirm this amount before deploying.",
    amountConfirmed: "Amount confirmed",
    confirming: "Confirming…",
    confirmAmount: "Confirm amount",
    setsAside: "This sets aside {monto} for this task. You'll confirm it once.",
    oneMore: "The budget is set up. One more confirmation locks the money.",
    secured: "Budget secured. The payment sends {monto}.",
    paymentSent: "Payment sent. Waiting for the network to show it as released. Do not pay again.",
    checkingBudget: "Checking the locked budget on the network. Refresh in a few seconds if nothing shows up.",
    paymentStillPending: "Payment sent. The network still hasn't shown it as released. Do not pay again.",
    budgetUnread: "We couldn't read the locked budget yet. Locking and paying stay off until we can, so nothing runs twice.",
    technical: "Technical details",
    yourAccount: "Your account {direccion}",
    budgetRef: "Budget reference {direccion}",
    paidAmount: "Paid {monto}",
    paidWait: "Paid. The blockchain link shows up once the network confirms it.",
    samplePay: "This is a sample. A live payment adds a link to the blockchain.",
    credential: "Credential",
    approve: "Approve",
    askAnother: "Ask for another photo",
    backEvent: "Back to the event",
    photoBroken: "This photo could not be shown.",
    loadingPhoto: "Loading photo",
    noLoad: "Could not load this review.",
    noAsk: "Could not ask for another photo.",
    manual: "Needs a manual review",
    copia: "This photo matches an earlier submission, so the recommendation stays at insufficient.",
    origenIa: "AI recommendation",
    origenMuestra: "Sample recommendation",
    origenFallo: "Review failed",
  },
  cuenta: {
    titulo: "Account",
    signOut: "Sign out",
    signingOut: "Signing out…",
    noLoad: "We couldn't load your account.",
    loading: "Loading account",
    demoNota: "Demo sample. These tasks and amounts are not payments on the network.",
    demoNotaMuestra: " The address and balance are a sample too.",
    demoNotaSesion: " The wallet is the one on this session.",
    wallet: "Wallet",
    signInWallet: "Sign in with a wallet to see your public address.",
    testnetUsdc: "Testnet USDC",
    sampleBalance: "Sample balance",
    onWallet: "On this wallet now",
    ausente: "This wallet is not on the test network yet. Open Events and tap Get ready to be paid.",
    noBalance: "We couldn't read the balance.",
    addWallet: "Add a wallet to see testnet USDC.",
    copy: "Copy address",
    copied: "Copied",
    viewTestnet: "View on testnet",
    copyHere: "Copy it from here. This is the public address.",
    thisMonth: "This month",
    lastMonth: "Last month",
    allTime: "All time",
    earnedEvents: "Earned from events",
    earningsByMonth: "Earnings by month",
    sinFecha: "Some payouts have no stored date, so they count in the all-time total only.",
    vacio: "Paid tasks will show up here, month by month.",
    vacioConPagos: "Completed tasks are here. A month appears once a payout has a date.",
    tasksPaid: "Tasks paid",
    noneYet: "None yet",
    milestonesReleased: "Milestones released",
    projectsFinished: "Projects finished",
    allTasksPaid: "All of your tasks paid",
    streak: "Streak",
    oneMonth: "1 month",
    months: "{n} months",
    inARow: "In a row",
    noPayoutMonth: "No payout month yet",
    bestMonth: "Best month",
    bestLater: "It will show after a payout",
    milestones: "Milestones",
    earned: "Earned",
    locked: "Locked",
    recent: "Recent paid tasks",
    nothingPaid: "Nothing paid yet. Finish a task and it will land here.",
    insigniaPrimera: "First task",
    insigniaPrimeraDetalle: "A paid task",
    insigniaCinco: "Five tasks",
    insigniaCincoDetalle: "Five paid tasks",
    insigniaDiez: "Ten tasks",
    insigniaDiezDetalle: "Ten paid tasks",
    insigniaProyecto: "First project",
    insigniaProyectoDetalle: "Every task in a project paid",
    insigniaTres: "Three projects",
    insigniaTresDetalle: "Three projects finished",
    insigniaRacha: "Three-month streak",
    insigniaRachaDetalle: "Earnings three months in a row",
    confirmWindow: "Confirm in the window if it asks. This can take a minute.",
    newAccount: "If this account is new, we'll open it on the test network first. You'll confirm once so it can receive the event payment.",
  },
  estados: {
    pendiente: "Pending",
    revision: "In review",
    pagado: "Paid",
  },
  veredictos: {
    cumplio: "Completed",
    parcial: "Partially completed",
    insuficiente: "Insufficient",
  },
  tipos: {
    trabajo: "Work",
    reembolso: "Reimbursement",
  },
  choices: {
    stand: "booth",
    factura: "receipt",
    trabajo: "work",
    otra: "other",
  },
  legado: {
    met: "met",
    notMet: "not met",
    category: " Category {choice}, condition {condicion}, evidence {evidencia}.",
  },
  pago: {
    lockBudget: "Lock budget",
    finishLocking: "Finish locking",
    settingUp: "Setting up…",
    locking: "Locking…",
    approvePay: "Approve and pay",
    checking: "Checking…",
    approving: "Approving…",
    paying: "Paying…",
    viewChain: "View on blockchain",
    checkAgain: "Check again",
    preparePayout: "Get ready to be paid",
    preparingPayout: "Getting ready…",
    payoutReady: "Ready to be paid",
    payoutDone: "Payout account ready",
    checkingPayout: "Checking your payout account…",
    saveProject: "Save project",
    reviewPhoto: "Review the photo",
    pay: "Pay",
    budgetNotLocked: "Budget not locked",
    paymentFailed: "Payment failed",
    noUsdcLeft: "No USDC left the escrow.",
    settingUpLong: "Setting up the budget. Keep this page open. It can take a minute.",
    lockingLong: "Locking the budget. Confirm in the window if it asks. It can take a minute.",
    recording: "Recording that the work is done.",
    approvingLong: "Approving the payment.",
    sending: "Sending the payment. Keep this page open.",
  },
  errores: {
    paso: "That step didn't go through. Try again.",
    noInicio: "We couldn't start that step. Try again.",
    noCompleto: "We couldn't complete that step. Try again.",
    noPresupuesto: "We couldn't check the budget. Try again.",
    noCobroFin: "We couldn't finish setting up payouts. Try again.",
    noCobroCheck: "We couldn't check whether this account can receive payment. Try again.",
    noCobroListo: "We couldn't get this account ready to receive payment. Try again.",
    noCobroConfirm: "We couldn't confirm the payout setup. Try again.",
    noCuentaPago: "We couldn't check the payout account. Try again.",
    entrarOtraVez: "Sign in again before you continue.",
    entrarContinuar: "Sign in to continue.",
    noTestnet: "This account isn't on the test network yet. Open Events and tap Get ready to be paid.",
    noPareceCuenta: "That doesn't look like a payout account. Sign in again.",
    noCoincideIngreso: "That account doesn't match this sign-in. Sign in again.",
    confirmacionNoCoincide: "The confirmation didn't match this sign-in. Sign in again and retry.",
    confirmacionNoLlego: "The confirmation didn't arrive. Try again.",
    confirmacionNoEnvio: "The confirmation couldn't be sent. Try again.",
    confirmacionNoCuenta: "That confirmation doesn't match this account. Try again.",
    noPreparar: "We couldn't prepare that step. Try again.",
    bloquearAntes: "Lock the budget before you pay.",
    presupuestoNoBloqueado: "The budget wasn't locked. Try Lock budget again.",
    yaBloqueado: "This task already has its budget locked.",
    enviadoSinContrato: "The budget was sent, but we couldn't confirm it yet. Refresh in a moment.",
    sinWalletVoluntario: "We don't have the volunteer's payout account yet. Ask them to sign in to Hyto and open the task.",
    esperaRevision: "Wait until the photo review finishes before locking the budget.",
    montoCero: "The amount has to be greater than zero.",
    soloOrganizador: "Only the organizer can lock the budget and pay.",
    soloResolver: "Only the person who resolves disputes can do this.",
    saldoRed: "This account needs a little test balance for the network fee. Add some and try again.",
    cancelaste: "You cancelled the confirmation. Nothing was sent.",
    reingreso: "Your sign-in expired. Sign in again to continue.",
    sinConfig: "Sign-in isn't set up yet.",
    cuentasNo: "Account setup isn't available yet.",
    cuentaNoAbrio: "The payout account didn't open. Try again.",
    demoCobro: "Demo mode can't set up payouts. Sign in with your email to continue.",
    demoPagos: "Demo mode can't send payments. Sign in with your email to continue.",
    servicioRechazo: "The payment service rejected that step. Try again.",
    receptorNoListo: "The volunteer's payout account isn't ready yet. Ask them to open Events in Hyto and tap Get ready to be paid.",
    horizonReceptor: "We couldn't reach the network to check the payout account. Try again.",
    listoCobro: "The person who gets paid isn't ready to receive it yet. They should open Events and tap Get ready to be paid.",
    faucetTestnet: "We couldn't open this payout account on the test network. Open Events and tap Get ready to be paid.",
    soloTestnet: "Payout accounts are only opened on the test network.",
    servidorIncompleto: "Payment setup isn't complete on the server. Ask whoever runs Hyto.",
    pagosNoDisponibles: "Payments aren't available right now. Ask whoever runs Hyto.",
    yaPagada: "This task is already paid.",
    saldoInsuficiente: "There isn't enough money set aside yet. Finish locking the budget, then pay.",
    codigoNo: "That code does not match. Check your email and try again.",
    codigoVencio: "That code expired. Request another one.",
    sinRed: "No connection. Check the network and try again.",
    googleCerrado: "You closed the Google window. Try again.",
    googleBloqueado: "The browser blocked the Google window. Allow it and try again.",
    correo: "Enter a valid email.",
    demoCorreo: "That demo email does not receive messages. Use a real email or sign in with Google.",
    spam: "The code arrives by email. Check spam too.",
    noEntrar: "Could not sign in. Try again.",
    montoInvalido: "Enter an amount greater than zero, with up to two decimals.",
    montoTope: "The amount cannot be higher than the limit.",
    montoTarde: "This payment is already set up.",
  },
};

type Rama<T> = {
  [K in keyof T]: T[K] extends string ? string : Rama<T[K]>;
};

export const es: Rama<typeof en> = {
  idioma: {
    grupo: "Idioma",
    en: "EN",
    es: "ES",
  },
  nav: {
    events: "Eventos",
    tasks: "Tareas",
    account: "Cuenta",
    main: "Principal",
    back: "Volver",
  },
  tema: {
    light: "Cambiar a tema claro",
    dark: "Cambiar a tema oscuro",
  },
  comunes: {
    loading: "Cargando…",
    tryAgain: "Intentar de nuevo",
    sample: "Ejemplo",
    event: "Evento",
    all: "Todas",
    amount: "Monto",
    date: "Fecha",
    unassigned: "Sin asignar",
    done: "Listo",
    now: "Ahora",
    later: "Después",
  },
  eventos: {
    title: "Eventos",
    create: "+ Crear",
    joinCode: "Unirme con un código",
    noLoad: "No pudimos cargar los eventos.",
    empty: "Todavía no hay eventos.",
    emptyHelp: "Crea uno o únete con un código.",
    member: "Integrante",
    organizer: "Organizador",
    team: "Equipo",
    volunteer: "Voluntario",
    toReview: "{n} por revisar",
    inReview: "{n} en revisión",
    invite: "Invitar",
    inviteRegion: "Invitar",
    createCode: "Crear un código",
    email: "Correo",
    inviteEmail: "Invitar por correo",
    copyLink: "Copiar enlace",
    copied: "Copiado",
    inviteFail: "No pudimos crear la invitación.",
    tablist: "Evento",
    inbox: "Bandeja",
    tasks: "Tareas",
    report: "Informe",
    noTasks: "Todavía no hay tareas.",
    assignedLater: "Cuando quien organiza te asigne una tarea, aparece aquí.",
    joinTitle: "Unirme con un código",
    code: "Código",
    join: "Unirme",
    joinInvalid: "Ese código no sirve.",
    assign: "Asignar",
    assignFail: "No pudimos asignar esa tarea.",
    createTitle: "Crear evento",
    newEvent: "Evento nuevo",
    name: "Nombre",
    taskN: "Tarea {n}",
    titleLabel: "Título",
    type: "Tipo",
    amount: "Monto (USDC)",
    photoMust: "La foto tiene que mostrar",
    assignee: "Asignar a",
    remove: "Quitar {name}",
    taskWord: "tarea",
    addTask: "Agregar tarea",
    budget: "Presupuesto",
    workTasks: "Tareas de trabajo",
    reimbursements: "Reembolsos",
    total: "Total",
    createEvent: "Crear evento",
    needFields: "Escribe un nombre y al menos una tarea con monto.",
    createFail: "No pudimos crear el evento.",
    demoCreate: "El modo demo no puede crear eventos. Entra con tu correo para crear uno.",
    reportLead: "El presupuesto comparado con lo pagado. Cada tarea es un pago.",
    print: "Imprimir",
    against: "Presupuesto y gasto",
    paidLine: "Pagado {paid} · Restante {pending} · {n} voluntario",
    paidLineMany: "Pagado {paid} · Restante {pending} · {n} voluntarios",
    detail: "Detalle",
    limit: "Límite {amount}",
    upTo: "Hasta {amount}",
    credential: "Credencial",
    sampleReport: "Informe de ejemplo, hasta que carguen las tareas reales. Una tarea pagada puede incluir el enlace de la cadena.",
    accountsTitle: "Cuentas y billetera",
    accountsLead: "Una persona organiza y tres son voluntarias. Cada quien confirma el código que le llega por correo. Después su cuenta puede recibir el pago del evento.",
    accountDetails: "Datos de la cuenta",
    notSetUp: "Todavía no está lista",
    readyReceive: "Lista para recibir el pago",
    notReadyReceive: "No está lista para recibir el pago",
    confirm: "Confirmar",
    preparing: "Preparando…",
    prepareAccounts: "Preparar cuentas",
    accountsReady: "Cuentas listas",
    prepareFail: "No pudimos preparar la cuenta.",
    codeLabel: "Código",
    codeFor: "Código para {name}",
    limitUsdc: "Límite (USDC)",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    saveFail: "No se pudo guardar esa tarea.",
    editOnly: "Solo quien organiza puede editar las tareas.",
    editPhoto: "Esta tarea ya tiene una foto, así que no se puede editar.",
    editPaid: "Esta tarea ya tiene un pago, así que no se puede editar.",
    editLocked: "El monto ya está bloqueado en el pago, así que esta tarea no se puede editar.",
    needTitle: "Escribe un título.",
    titleLong: "El título es muy largo.",
    needPhoto: "Escribe lo que tiene que mostrar la foto.",
    noteLong: "Esa nota es muy larga.",
    noCap: "Las tareas de trabajo no tienen un límite.",
    choosePerson: "Elige a alguien de este evento.",
    nothingSave: "No hay nada que guardar.",
    notInEvent: "Esa persona no está en este evento.",
  },
  bienvenida: {
    kicker: "Bienvenida",
    title: "Ya entraste.",
    body: "Hyto es un mercado de tareas cortas. Haz el trabajo, envía una foto y cobra en dólares digitales (USDC).",
    step: "Da tu primer paso",
  },
  landing: {
    esloganAntes: "Demuestra lo que vales.",
    esloganAcento: "Te pagan.",
    sub: "Haces tareas de proyectos reales, mandas una foto y te pagan en USDC.",
    legal: "El ingreso es con Cavos · tu billetera de Stellar se crea sola.",
    panel: "Cómo funciona Hyto",
    panelQ: "Bloquea el presupuesto. Revisa la foto. Paga el hito.",
    panelS: "Quien organiza revisa y aprueba desde una sola bandeja. Mile, la revisión con IA, lee cada foto; las personas deciden cada pago.",
    voluntarios: "Voluntarios",
    organizadores: "Organizadores",
    escrow: "Pago con depósito en Stellar",
  },
  entrar: {
    signIn: "Entrar",
    signUp: "Crear cuenta",
    newHere: "Nuevo en Hyto",
    welcomeBack: "Hola de nuevo",
    signUpBody:
      "Es tu primera vez. Creamos tu cuenta de Hyto y una billetera en la red de prueba de Stellar, la fondeamos con Friendbot si la cuenta no existe y la dejamos lista para recibir USDC.",
    signInBody:
      "Ya tienes cuenta y billetera. Google abre esa sesión. No creamos otra cuenta ni volvemos a preparar Stellar.",
    signedIn: "Sesión iniciada",
    accountDetails: "Datos de la cuenta",
    dialog: "Entrar",
    dialogSignUp: "Crear cuenta",
    title: "Entra a Hyto",
    titleSignUp: "Crea tu cuenta en Hyto",
    close: "Cerrar",
    intro: "Solo con Google. No usamos Friendbot, no agregamos la línea de confianza ni creamos otra billetera.",
    introSignUp: "Google crea tu cuenta y prepara la red de prueba de Stellar. También puedes usar tu correo.",
    googleSignUp: "Crear cuenta con Google",
    emailSignUp: "Crear cuenta con correo",
    back: "Volver",
    createAccount: "Crear cuenta",
    creatingAccount: "Creando cuenta…",
    settingUp: "Preparando tu billetera en la red de prueba de Stellar…",
    altaPendiente: "Abre Eventos y toca Preparar el cobro para terminar la configuración en la red de prueba de Stellar.",
    openEvents: "Abrir Eventos",
    emailCode: "Te enviamos un código por correo. No necesitas otra aplicación.",
    email: "Correo",
    sending: "Enviando…",
    sendCode: "Enviar código",
    or: "o",
    openingGoogle: "Abriendo Google…",
    google: "Entrar con Google",
    code: "Código",
    signingIn: "Entrando…",
    resend: "Reenviar código",
    tryDemo: "Probar el modo demo",
    noAccount: "No necesitas una cuenta",
    demoRole: "Rol de la sesión demo",
    organizerDemo: "Cuenta demo de organizador",
    volunteerDemo: "Cuenta demo de voluntario",
    enterDemo: "Entrar como demo",
    legal: "Cavos en la red de prueba de Stellar. Entrar abre la billetera que ya tienes.",
    legalSignUp:
      "Cavos en la red de prueba de Stellar. Crear cuenta genera la billetera, usa Friendbot si la cuenta no existe y agrega la línea de confianza de USDC.",
    switching: "Cambiando…",
    switchVolunteer: "Cambiar a la cuenta demo de voluntario",
    switchOrganizer: "Cambiar a la cuenta demo de organizador",
    leaving: "Saliendo…",
    leaveDemo: "Salir del demo",
    demoMode: "Modo demo",
    signInAgain: "Vuelve a entrar",
    espera: "Espera {n} s antes de pedir otro código",
    couldNotSignIn: "No se pudo entrar.",
    leaveDemoFail: "No se pudo salir del demo.",
    demoOpenFail: "No se pudo abrir el demo. Inténtalo de nuevo.",
  },
  tareas: {
    title: "Mis tareas",
    earned: "Ganado",
    inReview: "En revisión",
    toDo: "Por hacer",
    one: "tarea",
    many: "tareas",
    loading: "Cargando tareas…",
    emptyTitle: "Todavía no tienes tareas.",
    emptyBody: "Únete a un evento con un código.",
    join: "Unirme con un código",
    filter: "Filtrar tareas",
    sort: "Ordenar tareas",
    sortLabel: "Orden",
    sortDefault: "Por defecto",
    sortHighest: "Mayor pago",
    bestPaid: "Mejor pago",
    openCamera: "Abrir cámara",
    view: "Ver tarea",
  },
  evidencia: {
    back: "Volver a Mis tareas",
    sentAction: "Evidencia enviada, hay que corregir algo",
    sent: "Evidencia enviada",
    upload: "Subir evidencia",
    receiptHelp: "Sube el comprobante o la factura en PDF o en imagen. Quien organiza lo revisa y envía el pago.",
    photoHelp: "Toma la foto del trabajo terminado con la cámara. Quien organiza lo revisa y envía el pago.",
    fileSent: "Archivo enviado",
    photoSent: "Foto enviada",
    fixSuffix: " Quien organiza no puede enviar el pago hasta que esto se corrija.",
    organizerNow: "Quien organiza ya puede revisarla. Esta tarea se muestra como Pagada cuando envíen el dinero.",
    organizerApproves: "Quien organiza aprueba y después el pago sale del depósito.",
    organizerCall: "Quien organiza toma la decisión final",
    anotherMaybe: "Si la foto no se ve bien, pueden pedirte otra.",
    invoicePdf: "PDF de la factura",
    alt: "Evidencia",
    camera: "Vista de la cámara",
    receiptPlaceholder: "PDF o imagen del comprobante",
    workPlaceholder: "Foto del trabajo",
    choosePdf: "Elegir un PDF o una imagen",
    gallery: "Toma la foto ahora. No se aceptan fotos de la galería.",
    mustShow: "Tu foto tiene que mostrar",
    takePhoto: "Tomar foto",
    send: "Enviar",
    sending: "Enviando…",
    chooseFile: "Elegir un archivo",
    openCamera: "Abrir cámara",
    sendingNote: "Enviando la foto. La recomendación puede tardar unos segundos.",
    chooseAnother: "Elegir otro archivo",
    takeAnother: "Tomar otra",
    sendAnother: "Enviar otro archivo",
    sample: "Tarea de ejemplo, hasta que carguen las tuyas.",
    noCameraShow: "No se pudo mostrar la cámara.",
    noCamera: "No se pudo abrir la cámara. Permite la cámara e intenta de nuevo.",
    cameraNotReady: "La cámara todavía no está lista.",
    noPhoto: "No se pudo tomar la foto.",
    badFile: "Elige un PDF, JPEG, PNG o WebP.",
    useCamera: "Toma la foto con la cámara.",
    noSend: "No se pudo enviar. Intenta de nuevo.",
    noTask: "No encontramos esa tarea.",
  },
  bandeja: {
    inbox: "Bandeja",
    none: "Todavía no hay envíos.",
    oneWaiting: "{n} envío esperando tu revisión",
    manyWaiting: "{n} envíos esperando tu revisión",
    backExample: "Volver al ejemplo de ZEEK",
    filter: "Filtrar envíos",
    nothingApprove: "Nada por aprobar",
    whenPhoto: "Cuando alguien envía una foto, aparece aquí.",
    invite: "Invitar",
    create: "Crear evento",
    nothingView: "Nada en esta vista.",
    assign: "Asignar",
    review: "Revisar",
    recommendation: "Recomendación",
    noRecommendation: "Todavía no hay recomendación",
    photoMust: "La foto tiene que mostrar",
    mileSuggests: "Mile solo sugiere. Tú apruebas cada pago.",
    openReview: "Abrir la revisión",
    sample: "Evento de ejemplo, hasta que carguen las tareas reales.",
    updated: "Actualizado ahora",
    retry: "Reintentar la revisión",
    retrying: "Reintentando…",
    retryFail: "No se pudo reintentar la revisión.",
  },
  numeros: {
    budget: "Presupuesto",
    paid: "Pagado",
    pending: "Restante",
  },
  revision: {
    crumb: "Revisión de la evidencia",
    openInvoice: "Abrir la factura",
    sampleEvidence: "Evidencia de ejemplo",
    noPhoto: "Todavía no hay foto",
    waitingVolunteer: "Esperando a que la persona voluntaria envíe una.",
    steps: "Pasos del pago",
    sampleReview: "Revisión de ejemplo. La marca de pagado se queda en este dispositivo.",
    mileNo: "Mile no está disponible. No hay puntaje de IA para esta foto.",
    amountReceipt: "Monto en el comprobante",
    amountToPay: "Monto a pagar",
    upTo: "Hasta {monto}. Confirma este monto antes de desplegar.",
    amountConfirmed: "Monto confirmado",
    confirming: "Confirmando…",
    confirmAmount: "Confirmar monto",
    setsAside: "Esto aparta {monto} para esta tarea. Lo confirmas una vez.",
    oneMore: "El presupuesto ya está listo. Una confirmación más bloquea el dinero.",
    secured: "Presupuesto asegurado. El pago envía {monto}.",
    paymentSent: "Pago enviado. Esperamos a que la red lo muestre como liberado. No pagues otra vez.",
    checkingBudget: "Estamos revisando el presupuesto bloqueado en la red. Actualiza en unos segundos si no aparece nada.",
    paymentStillPending: "Pago enviado. La red todavía no lo muestra como liberado. No pagues otra vez.",
    budgetUnread: "Todavía no pudimos leer el presupuesto bloqueado. Bloquear y pagar siguen apagados hasta poder leerlo, para que nada se ejecute dos veces.",
    technical: "Detalles técnicos",
    yourAccount: "Tu cuenta {direccion}",
    budgetRef: "Referencia del presupuesto {direccion}",
    paidAmount: "Pagado {monto}",
    paidWait: "Pagado. El enlace de la cadena aparece cuando la red lo confirma.",
    samplePay: "Esto es un ejemplo. Un pago real agrega un enlace a la cadena.",
    credential: "Credencial",
    approve: "Aprobar",
    askAnother: "Pedir otra foto",
    backEvent: "Volver al evento",
    photoBroken: "No se pudo mostrar esta foto.",
    loadingPhoto: "Cargando la foto",
    noLoad: "No se pudo cargar esta revisión.",
    noAsk: "No se pudo pedir otra foto.",
    manual: "Necesita una revisión manual",
    copia: "Esta foto coincide con un envío anterior, así que la recomendación se queda en insuficiente.",
    origenIa: "Recomendación de la IA",
    origenMuestra: "Recomendación de ejemplo",
    origenFallo: "La revisión falló",
  },
  cuenta: {
    titulo: "Cuenta",
    signOut: "Salir",
    signingOut: "Saliendo…",
    noLoad: "No pudimos cargar tu cuenta.",
    loading: "Cargando la cuenta",
    demoNota: "Ejemplo del demo. Estas tareas y montos no son pagos en la red.",
    demoNotaMuestra: " La dirección y el saldo también son de ejemplo.",
    demoNotaSesion: " La billetera es la de esta sesión.",
    wallet: "Billetera",
    signInWallet: "Entra con una billetera para ver tu dirección pública.",
    testnetUsdc: "USDC de testnet",
    sampleBalance: "Saldo de ejemplo",
    onWallet: "En esta billetera ahora",
    ausente: "Esta billetera todavía no está en la red de prueba. Abre Eventos y toca Preparar el cobro.",
    noBalance: "No pudimos leer el saldo.",
    addWallet: "Agrega una billetera para ver el USDC de testnet.",
    copy: "Copiar dirección",
    copied: "Copiado",
    viewTestnet: "Ver en testnet",
    copyHere: "Cópiala desde aquí. Esta es la dirección pública.",
    thisMonth: "Este mes",
    lastMonth: "Mes pasado",
    allTime: "Total",
    earnedEvents: "Ganado en eventos",
    earningsByMonth: "Ingresos por mes",
    sinFecha: "Algunos pagos no tienen fecha guardada, así que solo cuentan en el total.",
    vacio: "Las tareas pagadas aparecen aquí, mes por mes.",
    vacioConPagos: "Las tareas completadas están aquí. Un mes aparece cuando un pago tiene fecha.",
    tasksPaid: "Tareas pagadas",
    noneYet: "Todavía ninguna",
    milestonesReleased: "Hitos liberados",
    projectsFinished: "Proyectos terminados",
    allTasksPaid: "Todas tus tareas pagadas",
    streak: "Racha",
    oneMonth: "1 mes",
    months: "{n} meses",
    inARow: "Seguidos",
    noPayoutMonth: "Todavía no hay un mes con pago",
    bestMonth: "Mejor mes",
    bestLater: "Aparece después de un pago",
    milestones: "Hitos",
    earned: "Ganado",
    locked: "Bloqueado",
    recent: "Tareas pagadas recientes",
    nothingPaid: "Todavía no hay pagos. Termina una tarea y aparece aquí.",
    insigniaPrimera: "Primera tarea",
    insigniaPrimeraDetalle: "Una tarea pagada",
    insigniaCinco: "Cinco tareas",
    insigniaCincoDetalle: "Cinco tareas pagadas",
    insigniaDiez: "Diez tareas",
    insigniaDiezDetalle: "Diez tareas pagadas",
    insigniaProyecto: "Primer proyecto",
    insigniaProyectoDetalle: "Todas las tareas de un proyecto pagadas",
    insigniaTres: "Tres proyectos",
    insigniaTresDetalle: "Tres proyectos terminados",
    insigniaRacha: "Racha de tres meses",
    insigniaRachaDetalle: "Ingresos tres meses seguidos",
    confirmWindow: "Confirma en la ventana si te lo pide. Puede tardar un minuto.",
    newAccount: "Si esta cuenta es nueva, primero la abrimos en la red de prueba. Confirmas una vez para que pueda recibir el pago del evento.",
  },
  estados: {
    pendiente: "Pendiente",
    revision: "En revisión",
    pagado: "Pagado",
  },
  veredictos: {
    cumplio: "Completado",
    parcial: "Parcialmente completado",
    insuficiente: "Insuficiente",
  },
  tipos: {
    trabajo: "Trabajo",
    reembolso: "Reembolso",
  },
  choices: {
    stand: "puesto",
    factura: "factura",
    trabajo: "trabajo",
    otra: "otra",
  },
  legado: {
    met: "cumplida",
    notMet: "no cumplida",
    category: " Categoría {choice}, condición {condicion}, evidencia {evidencia}.",
  },
  pago: {
    lockBudget: "Bloquear presupuesto",
    finishLocking: "Terminar de bloquear",
    settingUp: "Preparando…",
    locking: "Bloqueando…",
    approvePay: "Aprobar y pagar",
    checking: "Revisando…",
    approving: "Aprobando…",
    paying: "Pagando…",
    viewChain: "Ver en la cadena",
    checkAgain: "Revisar otra vez",
    preparePayout: "Preparar el cobro",
    preparingPayout: "Preparando…",
    payoutReady: "Listo para cobrar",
    payoutDone: "Cuenta de cobro lista",
    checkingPayout: "Revisando tu cuenta de cobro…",
    saveProject: "Guardar proyecto",
    reviewPhoto: "Revisar la foto",
    pay: "Pagar",
    budgetNotLocked: "Presupuesto sin bloquear",
    paymentFailed: "El pago falló",
    noUsdcLeft: "No salió USDC del depósito.",
    settingUpLong: "Preparando el presupuesto. Deja esta página abierta. Puede tardar un minuto.",
    lockingLong: "Bloqueando el presupuesto. Confirma en la ventana si te lo pide. Puede tardar un minuto.",
    recording: "Anotando que el trabajo está listo.",
    approvingLong: "Aprobando el pago.",
    sending: "Enviando el pago. Deja esta página abierta.",
  },
  errores: {
    paso: "Ese paso no se completó. Intenta de nuevo.",
    noInicio: "No pudimos empezar ese paso. Intenta de nuevo.",
    noCompleto: "No pudimos completar ese paso. Intenta de nuevo.",
    noPresupuesto: "No pudimos revisar el presupuesto. Intenta de nuevo.",
    noCobroFin: "No pudimos terminar de preparar el cobro. Intenta de nuevo.",
    noCobroCheck: "No pudimos revisar si esta cuenta puede recibir el pago. Intenta de nuevo.",
    noCobroListo: "No pudimos dejar esta cuenta lista para recibir el pago. Intenta de nuevo.",
    noCobroConfirm: "No pudimos confirmar la preparación del cobro. Intenta de nuevo.",
    noCuentaPago: "No pudimos revisar la cuenta de cobro. Intenta de nuevo.",
    entrarOtraVez: "Vuelve a entrar antes de continuar.",
    entrarContinuar: "Entra para continuar.",
    noTestnet: "Esta cuenta todavía no está en la red de prueba. Abre Eventos y toca Preparar el cobro.",
    noPareceCuenta: "Eso no parece una cuenta de cobro. Vuelve a entrar.",
    noCoincideIngreso: "Esa cuenta no coincide con este ingreso. Vuelve a entrar.",
    confirmacionNoCoincide: "La confirmación no coincidió con este ingreso. Vuelve a entrar e intenta de nuevo.",
    confirmacionNoLlego: "La confirmación no llegó. Intenta de nuevo.",
    confirmacionNoEnvio: "No se pudo enviar la confirmación. Intenta de nuevo.",
    confirmacionNoCuenta: "Esa confirmación no coincide con esta cuenta. Intenta de nuevo.",
    noPreparar: "No pudimos preparar ese paso. Intenta de nuevo.",
    bloquearAntes: "Bloquea el presupuesto antes de pagar.",
    presupuestoNoBloqueado: "El presupuesto no quedó bloqueado. Intenta Bloquear presupuesto otra vez.",
    yaBloqueado: "Esta tarea ya tiene el presupuesto bloqueado.",
    enviadoSinContrato: "El presupuesto se envió, pero todavía no pudimos confirmarlo. Actualiza en un momento.",
    sinWalletVoluntario: "Todavía no tenemos la cuenta de cobro de la persona voluntaria. Pídele que entre a Hyto y abra la tarea.",
    esperaRevision: "Espera a que termine la revisión de la foto antes de bloquear el presupuesto.",
    montoCero: "El monto tiene que ser mayor que cero.",
    soloOrganizador: "Solo quien organiza puede bloquear el presupuesto y pagar.",
    soloResolver: "Solo quien resuelve disputas puede hacer esto.",
    saldoRed: "Esta cuenta necesita un poco de saldo de prueba para la comisión de la red. Agrega un poco e intenta de nuevo.",
    cancelaste: "Cancelaste la confirmación. No se envió nada.",
    reingreso: "Tu ingreso venció. Vuelve a entrar para continuar.",
    sinConfig: "El ingreso todavía no está configurado.",
    cuentasNo: "La preparación de la cuenta todavía no está disponible.",
    cuentaNoAbrio: "La cuenta de cobro no se abrió. Intenta de nuevo.",
    demoCobro: "El modo demo no puede preparar cobros. Entra con tu correo para continuar.",
    demoPagos: "El modo demo no puede enviar pagos. Entra con tu correo para continuar.",
    servicioRechazo: "El servicio de pagos rechazó ese paso. Intenta de nuevo.",
    receptorNoListo: "La cuenta de cobro de la persona voluntaria todavía no está lista. Pídele que abra Eventos en Hyto y toque Preparar el cobro.",
    horizonReceptor: "No pudimos contactar la red para revisar la cuenta de cobro. Intenta de nuevo.",
    listoCobro: "Quien va a cobrar todavía no puede recibir el pago. Tiene que abrir Eventos y tocar Preparar el cobro.",
    faucetTestnet: "No pudimos abrir esta cuenta de cobro en la red de prueba. Abre Eventos y toca Preparar el cobro.",
    soloTestnet: "Las cuentas de cobro solo se abren en la red de prueba.",
    servidorIncompleto: "La configuración de pagos no está completa en el servidor. Avísale a quien administra Hyto.",
    pagosNoDisponibles: "Los pagos no están disponibles ahora. Avísale a quien administra Hyto.",
    yaPagada: "Esta tarea ya está pagada.",
    saldoInsuficiente: "Todavía no hay suficiente dinero apartado. Termina de bloquear el presupuesto y después paga.",
    codigoNo: "Ese código no coincide. Revisa tu correo e intenta de nuevo.",
    codigoVencio: "Ese código venció. Pide otro.",
    sinRed: "No hay conexión. Revisa la red e intenta de nuevo.",
    googleCerrado: "Cerraste la ventana de Google. Intenta de nuevo.",
    googleBloqueado: "El navegador bloqueó la ventana de Google. Permítela e intenta de nuevo.",
    correo: "Escribe un correo válido.",
    demoCorreo: "Ese correo de demo no recibe mensajes. Usa un correo real o entra con Google.",
    spam: "El código llega por correo. Revisa también el spam.",
    noEntrar: "No se pudo entrar. Intenta de nuevo.",
    montoInvalido: "Escribe un monto mayor que cero, con hasta dos decimales.",
    montoTope: "El monto no puede ser mayor que el límite.",
    montoTarde: "Este pago ya está preparado.",
  },
};

type Unir<T, P extends string = ""> = {
  [K in keyof T & string]: T[K] extends string ? `${P}${K}` : Unir<T[K], `${P}${K}.`>;
}[keyof T & string];

export type Clave = Unir<typeof en>;

export type FuenteTextos = {
  en: Rama<typeof en>;
  es: Rama<typeof en>;
};

export function rutas(valor: unknown, prefijo = ""): string[] {
  if (valor === null || typeof valor !== "object") return prefijo ? [prefijo] : [];
  const lista: string[] = [];
  for (const [clave, hijo] of Object.entries(valor as Record<string, unknown>)) {
    const ruta = prefijo ? `${prefijo}.${clave}` : clave;
    if (hijo !== null && typeof hijo === "object") lista.push(...rutas(hijo, ruta));
    else lista.push(ruta);
  }
  return lista;
}

function caminar(nodo: unknown, partes: string[]): unknown {
  let actual = nodo;
  for (const parte of partes) {
    if (!actual || typeof actual !== "object" || !(parte in actual)) return undefined;
    actual = (actual as Record<string, unknown>)[parte];
  }
  return actual;
}

export function leerTexto(idioma: Idioma, clave: string, fuente: FuenteTextos = { en, es }): string {
  const partes = clave.split(".");
  const propio = caminar(idioma === "es" ? fuente.es : fuente.en, partes);
  if (typeof propio === "string" && propio.length > 0) return propio;
  const ingles = caminar(fuente.en, partes);
  if (typeof ingles === "string" && ingles.length > 0) return ingles;
  return clave;
}

function aplicar(valor: string, vars?: Record<string, string | number>): string {
  if (!vars) return valor;
  return valor.replace(/\{(\w+)\}/g, (todo, nombre: string) => {
    const dato = vars[nombre];
    return dato === undefined ? todo : String(dato);
  });
}

export function texto(idioma: Idioma, clave: Clave, vars?: Record<string, string | number>): string {
  return aplicar(leerTexto(idioma, clave), vars);
}
