import type { Idioma } from "@/lib/ui/idioma";

/**
 * User-visible copy. English is the default and the fallback.
 * Add a key here and in `es` together; `lib/ui/diccionario.test.ts` checks they match.
 */
export const en = {
  idioma: {
    grupo: "Language",
    en: "EN",
    es: "ES",
  },
  nav: {
    events: "Events",
    tasks: "Tasks",
    account: "Account",
    main: "Main",
    back: "Back",
    join: "Join",
    joinCode: "Join with code",
    accountWallet: "Account & wallet",
    myTasks: "My tasks",
    cancel: "Cancel",
  },
  mile: {
    alt: {
      descansando: "Mile is resting",
      buscando: "Mile is checking your photo",
      laTengo: "Mile has it",
      rechazado: "Mile needs another photo",
      icono: "Mile",
      caraNeutra: "Mile",
      caraFeliz: "Mile is happy",
    },
    cumple: "This is in your photo.",
    parcial: "This is only partly in your photo.",
    noCumple: "This is missing from your photo.",
    notaSigue: "Your photo meets every point. The organizer reviews it next.",
    notaParcial: "Your photo is in. A point is only partly there. The organizer decides.",
    notaRechazo: "A point is missing. Take another photo and send it again.",
    notaTope: "Mile already checked the maximum number of attempts. The organizer decides.",
    topeAviso: "Mile already checked the maximum number of attempts.",
    requisitosLista: "Requirements have to be a list.",
    requisitosMax: "Enter at most 3 requirements.",
    demoSugerir: "Demo mode cannot suggest requirements.",
  },
  confirmar: {
    cancel: "Cancel",
    close: "Close",
    irreversible: "This can't be undone.",
    working: "…",
    to: "To",
    failed: "Could not finish. Try again.",
    lockTitle: "Lock this task's budget",
    lockDetail: "The money stays locked until you approve the work.",
    lockAction: "Lock {monto} USDC",
    finishTitle: "Finish locking the budget",
    finishDetail: "The first step worked. This last step locks the money.",
    payTitle: "Approve and pay",
    payDetail: "You approve the work and the payment goes to the person who did it.",
    payAction: "Pay {monto} USDC",
    inviteCodeTitle: "Create an invite code",
    inviteCodeDetail: "Anyone with the code can join this event for 7 days. Share it only with people you trust.",
    inviteCodeAction: "Create code",
    inviteEmailTitle: "Invite by email",
    inviteEmailDetail: "Only {email} can use this invite. It works once and expires in 7 days.",
    inviteEmailAction: "Send invite",
    accessNote: "People you invite join as volunteers and only see the tasks you assign to them.",
  },
  tema: {
    light: "Switch to light theme",
    dark: "Switch to dark theme",
  },
  comunes: {
    loading: "Loading…",
    tryAgain: "Try again",
    sample: "Sample",
    event: "Event",
    all: "All",
    amount: "Amount",
    date: "Date",
    unassigned: "Unassigned",
    done: "Done",
    now: "Now",
    later: "Later",
  },
  eventos: {
    title: "Events",
    create: "+ Create",
    joinCode: "Join with code",
    noLoad: "Could not load events.",
    empty: "No events yet.",
    emptyHelp: "Create one or join with a code.",
    member: "Member",
    organizer: "Organizer",
    team: "Team",
    volunteer: "Volunteer",
    toReview: "{n} to review",
    inReview: "{n} in review",
    invite: "Invite",
    inviteRegion: "Invite",
    closeInvite: "Close",
    createCode: "Create a code",
    email: "Email",
    inviteEmail: "Invite by email",
    copyLink: "Copy link",
    copied: "Copied",
    inviteFail: "Could not create the invite.",
    tablist: "Event",
    inbox: "Inbox",
    tasks: "Tasks",
    report: "Report",
    noTasks: "No tasks yet.",
    assignedLater: "When the organizer assigns you a task, it shows up here.",
    joinTitle: "Join with code",
    code: "Code",
    join: "Join",
    joinInvalid: "That code is not valid.",
    assign: "Assign",
    assignFail: "Could not assign that task.",
    createTitle: "Create event",
    newEvent: "New event",
    name: "Name",
    taskN: "Task {n}",
    titleLabel: "Title",
    type: "Type",
    amount: "Amount (USDC)",
    photoMust: "Photo must show",
    assignee: "Assign to",
    remove: "Remove {name}",
    taskWord: "task",
    addTask: "Add task",
    budget: "Budget",
    workTasks: "Work tasks",
    reimbursements: "Reimbursements",
    total: "Total",
    createEvent: "Create event",
    needFields: "Enter a name and at least one task with an amount.",
    createFail: "Could not create the event.",
    demoCreate: "Demo mode cannot create events. Sign in with your email to create one.",
    reportLead: "Budget compared with what has been paid. Each task is one payment.",
    print: "Print",
    against: "Budget against spend",
    paidLine: "Paid {paid} · Remaining {pending} · {n} volunteer",
    paidLineMany: "Paid {paid} · Remaining {pending} · {n} volunteers",
    detail: "Detail",
    limit: "Limit {amount}",
    upTo: "Up to {amount}",
    credential: "Credential",
    sampleReport: "Sample report, until live tasks load. A paid task can include a blockchain link.",
    accountsTitle: "Accounts & wallet",
    accountsLead: "One organizer and three volunteers. Each person confirms the code we email them. Then their account can receive the event payment.",
    accountDetails: "Account details",
    notSetUp: "Not set up yet",
    readyReceive: "Ready to receive payment",
    notReadyReceive: "Not ready to receive payment",
    confirm: "Confirm",
    preparing: "Preparing…",
    prepareAccounts: "Prepare accounts",
    accountsReady: "Accounts ready",
    prepareFail: "Could not prepare the account.",
    codeLabel: "Code",
    codeFor: "Code for {name}",
    limitUsdc: "Limit (USDC)",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    saveFail: "Could not save that task.",
    editOnly: "Only the organizer can edit tasks.",
    editPhoto: "This task already has a photo, so it can't be edited.",
    editPaid: "This task already has a payment, so it can't be edited.",
    editLocked: "The amount is already locked in the payment, so this task can't be edited.",
    needTitle: "Enter a title.",
    titleLong: "Title is too long.",
    needPhoto: "Enter what the photo must show.",
    noteLong: "That note is too long.",
    noCap: "Work tasks don't have a cap.",
    choosePerson: "Choose a person in this event.",
    nothingSave: "Nothing to save.",
    notInEvent: "That person is not in this event.",
  },
  bienvenida: {
    kicker: "Welcome",
    title: "You're in.",
    body: "Hyto is a marketplace of small tasks. Do the work, send a photo, and get paid in digital dollars (USDC).",
    step: "Take your first step",
  },
  landing: {
    esloganAntes: "Prove your worth,",
    esloganAcento: "get paid.",
    sub: "Do tasks for real projects, send a photo, get paid in USDC.",
    legal: "Sign-in by Cavos · your Stellar wallet is created for you.",
    panel: "How Hyto works",
    panelQ: "Lock the budget. Review the photo. Pay the milestone.",
    panelS: "Organizers review and approve from one inbox. Mile, the AI reviewer, reads each photo; people decide every payment.",
    voluntarios: "Volunteers",
    organizadores: "Organizers",
    escrow: "Paid via Stellar escrow",
  },
  entrar: {
    signIn: "Sign in",
    signUp: "Sign up",
    newHere: "New to Hyto",
    welcomeBack: "Welcome back",
    signUpBody: "First time here. We'll create your Hyto account and get it ready to receive payments.",
    signInBody:
      "You already have an account. Sign in with Google or with a code we email you. We won't create a new account.",
    signedIn: "Signed in",
    accountDetails: "Account details",
    dialog: "Sign in",
    dialogSignUp: "Sign up",
    title: "Sign in to Hyto",
    titleSignUp: "Sign up for Hyto",
    close: "Close",
    intro: "With your Google account or with a code we email you.",
    introSignUp: "Use Google or your email. We'll create your account and get it ready for your payments.",
    googleSignUp: "Sign up with Google",
    emailSignUp: "Sign up with email",
    back: "Back",
    createAccount: "Create account",
    creatingAccount: "Creating account…",
    settingUp: "Setting up your account…",
    altaPendiente: "Open Events and tap Get ready to be paid to finish setting up your account.",
    openEvents: "Open Events",
    emailCode: "We'll email you a code. You don't need a separate app.",
    email: "Email",
    sending: "Sending…",
    sendCode: "Send code",
    or: "or",
    openingGoogle: "Opening Google…",
    openingApple: "Opening Apple…",
    google: "Sign in with Google",
    code: "Code",
    signingIn: "Signing in…",
    resend: "Resend code",
    tryDemo: "Try demo mode",
    noAccount: "No account needed",
    demoRole: "Demo session role",
    organizerDemo: "Organizer demo account",
    volunteerDemo: "Volunteer demo account",
    enterDemo: "Enter as demo",
    legal: "Sign-in by Cavos. Signing in opens the account you already have.",
    legalSignUp: "Sign-in by Cavos. An account is created to hold your payment.",
    switching: "Switching…",
    switchVolunteer: "Switch to the volunteer demo account",
    switchOrganizer: "Switch to the organizer demo account",
    leaving: "Leaving…",
    leaveDemo: "Leave demo",
    demoMode: "Demo mode",
    signInAgain: "Sign in again",
    espera: "Wait {n} s before requesting another code",
    couldNotSignIn: "Could not sign in.",
    leaveDemoFail: "Could not leave demo mode.",
    demoOpenFail: "Could not open the demo. Try again.",
    sub: "Do tasks for real projects, send a photo, and get paid in USDC. Mile checks the proof; a person approves every payment.",
    chipEnviando: "Mile is searching…",
    chipCodigo: "Your code is on its way",
    chipError: "Something didn't add up",
    chipExito: "All set!",
    pestanas: "Sign in or create an account",
    paso: "Step {n} of 3",
    pasoCorreo: "Email",
    pasoCodigo: "Code",
    pasoListo: "Done",
    googleContinuar: "Continue with Google",
    appleContinuar: "Continue with Apple",
    oCorreo: "or with your email",
    correoEjemplo: "you@example.com",
    ayudaCorreo: "We'll send you a 6-digit code. Check spam too.",
    continuarCorreo: "Continue with email",
    enviandoCodigo: "Sending code…",
    cambiarCorreo: "Change email",
    revisaCorreo: "Check your email",
    enviamosA: "We sent a 6-digit code to",
    digito: "Digit {n} of 6",
    autoConfirma: "It confirms on its own when you type the last digit.",
    noLlego: "Didn't get it?",
    reenviarEn: "Resend code in {t}",
    pedirOtro: "Request another code",
    usarOtro: "Use another email",
    irCrearCuenta: "Create an account instead",
    probarOtraVez: "Try again",
    codigoMalTitulo: "That code doesn't match.",
    codigoMalCuerpo: "Check your email and try again.",
    codigoVencidoTitulo: "That code expired.",
    codigoVencidoCuerpo: "Request another one and we'll send it to the same email.",
    yaEntraste: "You're in.",
    llevando: "Signed in. Taking you in…",
    irTareas: "Continue",
    soloMirar: "Just want to look?",
    probarDemo: "Try the demo",
    ayudaEnlace: "We'll email you a sign-in link. Check spam too.",
    enviandoEnlace: "Sending link…",
    chipEnlace: "Your link is on its way",
    pasoEnlace: "Link",
    enviamosEnlace: "We sent a sign-in link to",
    abrirEnlace: "Open it in this browser to finish. You can close this tab after.",
    reenviarEnlace: "Resend link",
    reenviarEnlaceEn: "Resend link in {t}",
    mile: {
      dive: "Mile is looking for your code…",
      code: "Mile brought your code.",
      worry: "Mile couldn't use that code.",
      win: "Mile found it. You're in.",
    },
  },
  tareas: {
    title: "My tasks",
    earned: "Earned",
    inReview: "In review",
    toDo: "To do",
    one: "task",
    many: "tasks",
    loading: "Loading tasks…",
    emptyTitle: "No tasks yet",
    emptyBody: "Join an event with the code the organizer gave you and your tasks show up here.",
    join: "Join with code",
    viewEvents: "See events",
    hello: "Hi, {name}!",
    helloNoName: "Hi!",
    youHave: "You have {n} tasks to do.",
    youHaveOne: "You have 1 task to do.",
    allDone: "You're all caught up. Mile will tell you when something new arrives.",
    filterAll: "All",
    filterPending: "Pending",
    filterSent: "Sent",
    filterDone: "Done",
    badgePending: "Pending",
    badgeSent: "Sent",
    badgePaid: "Paid",
    badgeRejected: "Rejected",
    takeAnotherPhoto: "Take another photo",
    chooseAnotherFile: "Choose another file",
    mileChecks: "Mile checks {n} points in your photo before it goes to the organizer.",
    mileChecksOne: "Mile checks your photo before it goes to the organizer.",
    mileReviewing: "Mile is checking your photo",
    paidNote: "Paid · {amount} in your wallet",
    due: "Due {when}",
    loadingMile: "Mile is bringing your tasks…",
    eventsCount: "{n} events",
    earnedUsdc: "{amount} earned",
    inReviewShort: "in review",
    toDoShort: "to do",
    sortMenu: "Sort",
    uploadEvidence: "Upload evidence",
    howItWorks: "How it works",
    step1: "You join the event with the organizer's code.",
    step2: "You do the task and upload a photo.",
    step3: "Mile checks it, the organizer approves and you get paid in USDC.",
    emptyPendingTitle: "You have no pending tasks. Everything is sent!",
    emptyPendingAction: "See sent",
    emptySentTitle: "No photos are waiting for review.",
    emptySentAction: "See pending",
    emptyDoneTitle: "None of your tasks have been paid yet. When the organizer approves a photo, it shows up here.",
    emptyDoneAction: "See pending",
    hideWelcome: "Hide",
    filter: "Filter tasks",
    sort: "Sort tasks",
    sortLabel: "Sort",
    sortPriority: "Priority",
    sortDefault: "Default",
    sortHighest: "Highest pay",
    bestPaid: "Best paid",
    upTo: "Up to {monto}",
    openCamera: "Open camera",
    view: "View task",
  },
  evidencia: {
    back: "Back to My tasks",
    sentAction: "Evidence sent, action needed",
    sent: "Evidence sent",
    upload: "Upload evidence",
    tabs: "What you are sending",
    tabReceipt: "Receipt",
    tabTask: "Task",
    mismatchReceipt: "This task needs a camera photo. Go back to the Task tab.",
    mismatchTask: "This task needs a receipt as a PDF or image. Go back to the Receipt tab.",
    backToTask: "Go back to Task",
    backToReceipt: "Go back to Receipt",
    receiptHelp: "Upload the receipt or invoice as a PDF or an image. The organizer checks it and sends the payment.",
    photoHelp: "Photograph the finished work with the camera. The organizer checks it and sends the payment.",
    fileSent: "File sent",
    photoSent: "Photo sent",
    uploaded: "Photo uploaded successfully",
    reachedOrganizer: "Your photo already reached the organizer",
    fixSuffix: " The organizer can't send the payment until this is fixed.",
    organizerNow: "The organizer can review it now. This task shows Paid after they send the money.",
    organizerApproves: "The organizer approves, then you get paid.",
    organizerCall: "Your organizer makes the final call",
    anotherMaybe: "If the photo isn't clear, the organizer may ask for another one.",
    invoicePdf: "Invoice PDF",
    alt: "Evidence",
    camera: "Camera preview",
    receiptPlaceholder: "PDF or image of the receipt",
    workPlaceholder: "Photo of the work",
    choosePdf: "Choose a PDF or image",
    gallery: "Take the photo now. Photos from the gallery are not accepted.",
    mustShow: "Your photo must show",
    takePhoto: "Take photo",
    send: "Send evidence",
    sending: "Sending…",
    chooseFile: "Choose a file",
    openCamera: "Open camera",
    sendingNote: "Sending the photo. The recommendation can take a few seconds.",
    chooseAnother: "Choose another file",
    takeAnother: "Take another",
    sendAnother: "Send another file",
    sample: "Sample task, until your own tasks load.",
    noCameraShow: "Could not show the camera.",
    noCamera: "Could not open the camera. Allow the camera and try again.",
    cameraNotReady: "The camera is not ready yet.",
    noPhoto: "Could not take the photo.",
    badFile: "Choose a PDF, JPEG, PNG, or WebP file.",
    useCamera: "Take the photo with the camera.",
    noSend: "Could not send. Try again.",
    sendFailed: "Could not send. Check your connection and try again.",
    sendUnconfirmed: "The server did not confirm the upload. Try again.",
    sendUnknown: "The connection dropped before Hyto confirmed the upload. Open My tasks to check before you send it again.",
    noTask: "We couldn't find that task.",
    mileHi: "HI, I'M MILE",
    mileCheck: "Before you send it, I check your photo",
    mileWhy: "That way it reaches the organizer complete and you get paid faster.",
    cameraOff: "Camera off. Turn it on to take the photo.",
    galleryHint: "Take it now with the camera: old gallery photos are not accepted.",
    onePhoto: "1 photo",
    sendEvidence: "Send evidence",
    takePhotoFirst: "Take the photo first",
    chooseFirst: "Choose your photo first",
    checking: "Checking",
    mileChecking: "Mile is checking your photo",
    fewSeconds: "It takes a few seconds. You can wait here.",
    sentShort: "Sent",
    willTell: "We'll let you know when the organizer decides.",
    greatJob: "Great job! Your photo arrived",
    greatJobName: "Great job, {name}! Your photo arrived",
    greatJobSub: "We'll let you know as soon as the organizer approves it.",
    sentAt: "{event} · sent {time}",
    whatNow: "What happens now",
    stepMile: "Mile checks your photo",
    stepOrganizer: "The organizer approves",
    stepPay: "You get paid",
    stepPayAmount: "{amount} to your wallet",
    now: "Now",
    backToTasks: "Back to my tasks",
    taskRejected: "Task rejected",
    missingPoint: "Missing: {point}",
    organizerAsked: "The organizer asked for another photo",
    retakeFrame: "Take another photo with everything that's asked inside the frame.",
    restFine: "Everything else is fine.",
    howPhoto: "How your photo turned out",
    notInPhoto: "Not in the photo",
    organizerRole: "{name} · organizer",
    sendUntil: "You can send it until {when}",
    deadlineClosed: "The deadline for this task has passed",
    deadlineTalk: "Talk to the organizer if you need more time.",
    askedAnother: "Asked for another photo",
    attempt: "Attempt {n}",
    youDidIt: "You did it! {name} approved your photo.",
    youDidItNoName: "You did it! They approved your photo.",
    youGotPaid: "You got paid",
    paidFor: "For \"{title}\". It's already in your wallet.",
    taskPayment: "Task payment",
    youReceived: "You received",
    viewReceipt: "View receipt",
    viewWallet: "View my wallet",
    keepGoing: "Keep going with my tasks",
    stepOrganizerName: "The organizer approves ({name} decides)",
    photoSentAt: "Photo sent · {time}",
    useCameraShort: "Use camera",
    closePaid: "Close",
  },
  bandeja: {
    inbox: "Inbox",
    none: "No submissions yet.",
    oneWaiting: "{n} submission waiting for your review",
    manyWaiting: "{n} submissions waiting for your review",
    backExample: "Back to the ZEEK example",
    filter: "Filter submissions",
    nothingApprove: "Nothing to approve",
    whenPhoto: "When someone sends a photo, it shows up here.",
    invite: "Invite",
    create: "Create event",
    nothingView: "Nothing in this view.",
    assign: "Assign",
    review: "Review",
    recommendation: "Recommendation",
    noRecommendation: "No recommendation yet",
    photoMust: "Photo must show",
    mileSuggests: "Mile only suggests. You approve every payment.",
    openReview: "Open review",
    sample: "Sample event, until live tasks load.",
    updated: "Updated just now",
    retry: "Retry review",
    retrying: "Retrying…",
    retryFail: "The review could not be retried.",
  },
  numeros: {
    budget: "Budget",
    paid: "Paid",
    pending: "Remaining",
  },
  revision: {
    crumb: "Evidence review",
    openInvoice: "Open the invoice",
    sampleEvidence: "Sample evidence",
    noPhoto: "No photo yet",
    waitingVolunteer: "Waiting for the volunteer to send one.",
    steps: "Payment steps",
    sampleReview: "Sample review. The paid mark here stays on this device.",
    mileNo: "Mile is unavailable. No AI score for this photo.",
    amountReceipt: "Amount on the receipt",
    notShown: "Not shown",
    printedConverted: "Printed {monto}, converted at {tasa} {moneda} per US dollar.",
    printedNotConverted: "Printed {monto}. No currency Hyto can convert, so it was not converted to US dollars.",
    printedDate: "Printed {fecha}, which could not be read as a date.",
    amountToPay: "Amount to pay",
    upTo: "Up to {monto}. Confirm this amount before deploying.",
    amountConfirmed: "Amount confirmed",
    confirming: "Confirming…",
    confirmAmount: "Confirm amount",
    setsAside: "This sets aside {monto} for this task. You'll confirm it once.",
    oneMore: "The budget is set up. One more confirmation locks the money.",
    secured: "Budget secured. The payment sends {monto}.",
    paymentSent: "Payment sent. Waiting for the network to show it as released. Do not pay again.",
    checkingBudget: "Checking the locked budget on the network. Refresh in a few seconds if nothing shows up.",
    paymentStillPending: "Payment sent. The network still hasn't shown it as released. Do not pay again.",
    budgetUnread: "We couldn't read the locked budget yet. Locking and paying stay off until we can, so nothing runs twice.",
    technical: "Technical details",
    yourAccount: "Your account {direccion}",
    budgetRef: "Budget reference {direccion}",
    paidAmount: "Paid {monto}",
    paidWait: "Paid. The blockchain link shows up once the network confirms it.",
    samplePay: "This is a sample. A live payment adds a link to the blockchain.",
    credential: "Credential",
    approve: "Approve",
    askAnother: "Ask for another photo",
    whatsMissing: "What's missing?",
    messageFor: "Message for {name} (optional)",
    cancelAsk: "Cancel",
    backEvent: "Back to the event",
    photoBroken: "This photo could not be shown.",
    loadingPhoto: "Loading photo",
    noLoad: "Could not load this review.",
    noAsk: "Could not ask for another photo.",
    manual: "Needs a manual review",
    copia: "This photo matches an earlier submission, so the recommendation stays at insufficient.",
    origenIa: "AI recommendation",
    origenMuestra: "Sample recommendation",
    origenFallo: "Review failed",
  },
  cuenta: {
    titulo: "Account",
    signOut: "Sign out",
    signingOut: "Signing out…",
    noLoad: "We couldn't load your account.",
    loading: "Loading account",
    demoNota: "Demo sample. These tasks and amounts are not payments on the network.",
    demoNotaMuestra: " The address and balance are a sample too.",
    demoNotaSesion: " The wallet is the one on this session.",
    wallet: "Wallet",
    signInWallet: "Sign in with a wallet to see your public address.",
    testnetUsdc: "USDC",
    sampleBalance: "Sample balance",
    onWallet: "On this wallet now",
    ausente: "This wallet is not on the test network yet. Open Events and tap Get ready to be paid.",
    noBalance: "We couldn't read the balance.",
    addWallet: "Add a wallet to see your USDC.",
    copy: "Copy address",
    copied: "Copied",
    viewTestnet: "View in the explorer",
    copyHere: "Copy it from here. This is the public address.",
    thisMonth: "This month",
    lastMonth: "Last month",
    allTime: "All time",
    earnedEvents: "Earned from events",
    earningsByMonth: "Earnings by month",
    sinFecha: "Some payouts have no stored date, so they count in the all-time total only.",
    vacio: "Paid tasks will show up here, month by month.",
    vacioConPagos: "Completed tasks are here. A month appears once a payout has a date.",
    tasksPaid: "Tasks paid",
    noneYet: "None yet",
    milestonesReleased: "Milestones released",
    projectsFinished: "Projects finished",
    allTasksPaid: "All of your tasks paid",
    streak: "Streak",
    oneMonth: "1 month",
    months: "{n} months",
    inARow: "In a row",
    noPayoutMonth: "No payout month yet",
    bestMonth: "Best month",
    bestLater: "It will show after a payout",
    milestones: "Milestones",
    earned: "Earned",
    locked: "Locked",
    recent: "Recent paid tasks",
    nothingPaid: "Nothing paid yet. Finish a task and it will land here.",
    insigniaPrimera: "First task",
    insigniaPrimeraDetalle: "A paid task",
    insigniaCinco: "Five tasks",
    insigniaCincoDetalle: "Five paid tasks",
    insigniaDiez: "Ten tasks",
    insigniaDiezDetalle: "Ten paid tasks",
    insigniaProyecto: "First project",
    insigniaProyectoDetalle: "Every task in a project paid",
    insigniaTres: "Three projects",
    insigniaTresDetalle: "Three projects finished",
    insigniaRacha: "Three-month streak",
    insigniaRachaDetalle: "Earnings three months in a row",
    confirmWindow: "Confirm in the window if it asks. This can take a minute.",
    newAccount: "If this account is new, we'll open it on the test network first. You'll confirm once so it can receive the event payment.",
    pasaporteTitulo: "Stellar Passport",
    pasaporteDetalle: "It records participation and achievements in the Stellar ecosystem.",
    pasaporteAbrir: "Open Stellar Passport",
    passkeyTitulo: "Use Hyto on other devices",
    passkeyDetalle:
      "Your account key is stored in this browser. Add a passkey so your phone or another computer can open it too. Save the passkey where you keep your passwords. It works like a key to your account, so keep it to yourself.",
    passkeyAgregar: "Add a passkey",
    passkeyAgregando: "Adding…",
    passkeyListo: "Passkey added. On another device, sign in to Hyto and choose Use passkey when it asks.",
    passkeyAviso: "Add a passkey on Account to use Hyto on your other devices.",
  },
  estados: {
    pendiente: "Pending",
    revision: "In review",
    pagado: "Paid",
  },
  veredictos: {
    cumplio: "Completed",
    parcial: "Partially completed",
    insuficiente: "Insufficient",
  },
  tipos: {
    trabajo: "Work",
    reembolso: "Reimbursement",
  },
  choices: {
    stand: "booth",
    factura: "receipt",
    trabajo: "work",
    otra: "other",
  },
  clasificacion: {
    priority: "Priority",
    difficulty: "Difficulty",
    normal: "Normal",
    high: "High",
    highPriority: "High priority",
    notSet: "Not set",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    saveFail: "Could not save priority and difficulty.",
    onlyOrganizer: "Only the organizer can set priority and difficulty.",
    choosePriority: "Choose Normal or High.",
    chooseDifficulty: "Choose Easy, Medium, Hard, or Not set.",
  },
  legado: {
    met: "met",
    notMet: "not met",
    category: " Category {choice}, condition {condicion}, evidence {evidencia}.",
  },
  pago: {
    lockBudget: "Lock budget",
    finishLocking: "Finish locking",
    settingUp: "Setting up…",
    locking: "Locking…",
    approvePay: "Approve and pay",
    checking: "Checking…",
    approving: "Approving…",
    paying: "Paying…",
    viewChain: "View on blockchain",
    checkAgain: "Check again",
    preparePayout: "Get ready to be paid",
    preparingPayout: "Getting ready…",
    payoutReady: "Ready to be paid",
    payoutDone: "Payout account ready",
    checkingPayout: "Checking your payout account…",
    saveProject: "Save project",
    reviewPhoto: "Review the photo",
    pay: "Pay",
    budgetNotLocked: "Budget not locked",
    paymentFailed: "Payment failed",
    noUsdcLeft: "No USDC left the escrow.",
    settingUpLong: "Setting up the budget. Keep this page open. It can take a minute.",
    lockingLong: "Locking the budget. Confirm in the window if it asks. It can take a minute.",
    recording: "Recording that the work is done.",
    approvingLong: "Approving the payment.",
    sending: "Sending the payment. Keep this page open.",
  },
  errores: {
    paso: "That step didn't go through. Try again.",
    noInicio: "We couldn't start that step. Try again.",
    noCompleto: "We couldn't complete that step. Try again.",
    noPresupuesto: "We couldn't check the budget. Try again.",
    noCobroFin: "We couldn't finish setting up payouts. Try again.",
    noCobroCheck: "We couldn't check whether this account can receive payment. Try again.",
    noCobroListo: "We couldn't get this account ready to receive payment. Try again.",
    noCobroConfirm: "We couldn't confirm the payout setup. Try again.",
    noCuentaPago: "We couldn't check the payout account. Try again.",
    dispositivo:
      "This browser doesn't have your account key yet. Open Hyto once in the browser where you signed up, go to Account and tap Add a passkey. Then try again here and use that passkey.",
    passkey: "Confirm with your passkey to use your account in this browser. Try again and choose Use passkey when it asks.",
    passkeySinSoporte: "This browser can't create a passkey. Try a current version of Chrome, Safari or Edge.",
    passkeySinClave:
      "This browser doesn't have your account key, so it can't add a passkey. Open Hyto in the browser where you signed up and add it there.",
    passkeyCancelada: "You cancelled. No passkey was added.",
    passkeyFallo: "We couldn't add the passkey. Try again.",
    cobroSinXlm: "This payout account has no test XLM for the network fee. Try again in a few minutes, or ask whoever runs Hyto.",
    cobroSecuencia: "The payout account changed while it was getting ready. Try again.",
    cobroFirmante: "This sign-in can't confirm for this payout account. Sign in again and retry.",
    cobroVencido: "That confirmation expired before it reached the network. Try again.",
    cobroPendiente: "The network hasn't confirmed the payout setup yet. Wait a moment and try again.",
    cobroOtraCuenta: "This sign-in opened a different payout account than the one Hyto has for you. Sign in again and retry.",
    cobroLento: "The confirmation took too long. Check your connection and try again.",
    entrarOtraVez: "Sign in again before you continue.",
    entrarContinuar: "Sign in to continue.",
    noTestnet: "This account isn't on the test network yet. Open Events and tap Get ready to be paid.",
    noPareceCuenta: "That doesn't look like a payout account. Sign in again.",
    noCoincideIngreso: "That account doesn't match this sign-in. Sign in again.",
    confirmacionNoCoincide: "The confirmation didn't match this sign-in. Sign in again and retry.",
    confirmacionNoLlego: "The confirmation didn't arrive. Try again.",
    confirmacionNoEnvio: "The confirmation couldn't be sent. Try again.",
    confirmacionNoCuenta: "That confirmation doesn't match this account. Try again.",
    noPreparar: "We couldn't prepare that step. Try again.",
    bloquearAntes: "Lock the budget before you pay.",
    presupuestoNoBloqueado: "The budget wasn't locked. Try Lock budget again.",
    yaBloqueado: "This task already has its budget locked.",
    enviadoSinContrato: "The budget was sent, but we couldn't confirm it yet. Refresh in a moment.",
    sinWalletVoluntario: "We don't have the volunteer's payout account yet. Ask them to sign in to Hyto and open the task.",
    esperaRevision: "Wait until the photo review finishes before locking the budget.",
    montoCero: "The amount has to be greater than zero.",
    soloOrganizador: "Only the organizer can lock the budget and pay.",
    soloResolver: "Only the person who resolves disputes can do this.",
    saldoRed: "This account needs a little test balance for the network fee. Add some and try again.",
    cancelaste: "You cancelled the confirmation. Nothing was sent.",
    reingreso: "Your sign-in expired. Sign in again to continue.",
    sinConfig: "Sign-in isn't set up yet.",
    cuentasNo: "Account setup isn't available yet.",
    cuentaNoAbrio: "The payout account didn't open. Try again.",
    demoCobro: "Demo mode can't set up payouts. Sign in with your email to continue.",
    demoPagos: "Demo mode can't send payments. Sign in with your email to continue.",
    servicioRechazo: "The payment service rejected that step. Try again.",
    receptorNoListo: "The volunteer's payout account isn't ready yet. Ask them to open Events in Hyto and tap Get ready to be paid.",
    horizonReceptor: "We couldn't reach the network to check the payout account. Try again.",
    listoCobro: "The person who gets paid isn't ready to receive it yet. They should open Events and tap Get ready to be paid.",
    faucetTestnet: "We couldn't open this payout account on the test network. Open Events and tap Get ready to be paid.",
    soloTestnet: "Payout accounts are only opened on the test network.",
    servidorIncompleto: "Payment setup isn't complete on the server. Ask whoever runs Hyto.",
    pagosNoDisponibles: "Payments aren't available right now. Ask whoever runs Hyto.",
    yaPagada: "This task is already paid.",
    saldoInsuficiente: "There isn't enough money set aside yet. Finish locking the budget, then pay.",
    codigoNo: "That code does not match. Check your email and try again.",
    codigoVencio: "That code expired. Request another one.",
    sinRed: "No connection. Check the network and try again.",
    googleCerrado: "You closed the Google window. Try again.",
    googleBloqueado: "The browser blocked the Google window. Allow it and try again.",
    correo: "Enter a valid email.",
    demoCorreo: "That demo email does not receive messages. Use a real email or sign in with Google.",
    spam: "The code arrives by email. Check spam too.",
    spamEnlace: "The link arrives by email. Check spam too.",
    metodoRecuperacion: "This account needs a different sign-in. Use the sign-in option shown and try again.",
    sinRespaldo:
      "This account can't be opened in this browser yet. Open Hyto once in the browser where you signed up, then try again here.",
    noEntrar: "Could not sign in. Try again.",
    sinCuenta: "No Hyto account for this sign-in. Sign up first.",
    montoInvalido: "Enter an amount greater than zero, with up to two decimals.",
    montoTope: "The amount cannot be higher than the limit.",
    montoTarde: "This payment is already set up.",
  },
};

type Rama<T> = {
  [K in keyof T]: T[K] extends string ? string : Rama<T[K]>;
};

export const es: Rama<typeof en> = {
  idioma: {
    grupo: "Idioma",
    en: "EN",
    es: "ES",
  },
  nav: {
    events: "Eventos",
    tasks: "Tareas",
    account: "Cuenta",
    main: "Principal",
    back: "Volver",
    join: "Unirme",
    joinCode: "Unirme con código",
    accountWallet: "Cuenta y billetera",
    myTasks: "Mis tareas",
    cancel: "Cancelar",
  },
  mile: {
    alt: {
      descansando: "Mile está descansando",
      buscando: "Mile está revisando tu foto",
      laTengo: "Mile la tiene",
      rechazado: "Mile necesita otra foto",
      icono: "Mile",
      caraNeutra: "Mile",
      caraFeliz: "Mile está feliz",
    },
    cumple: "Esto sí está en tu foto.",
    parcial: "Esto está solo en parte en tu foto.",
    noCumple: "Esto no aparece en tu foto.",
    notaSigue: "Tu foto cumple cada punto. El organizador la revisa ahora.",
    notaParcial: "Tu foto llegó. Un punto está solo en parte. El organizador decide.",
    notaRechazo: "Falta un punto. Toma otra foto y envíala de nuevo.",
    notaTope: "Mile ya revisó el máximo de intentos. El organizador decide.",
    topeAviso: "Mile ya revisó el máximo de intentos.",
    requisitosLista: "Los requisitos tienen que ir en una lista.",
    requisitosMax: "Escribe como máximo 3 requisitos.",
    demoSugerir: "El modo de prueba no sugiere requisitos.",
  },
  confirmar: {
    cancel: "Cancelar",
    close: "Cerrar",
    irreversible: "Esta acción no se puede deshacer.",
    working: "…",
    to: "Para",
    failed: "No se pudo terminar. Inténtalo de nuevo.",
    lockTitle: "Bloquear el presupuesto de esta tarea",
    lockDetail: "El dinero queda bloqueado hasta que apruebes el trabajo.",
    lockAction: "Bloquear {monto} USDC",
    finishTitle: "Terminar de bloquear el presupuesto",
    finishDetail: "El primer paso funcionó. Este último paso bloquea el dinero.",
    payTitle: "Aprobar y pagar",
    payDetail: "Apruebas el trabajo y el pago llega a quien lo hizo.",
    payAction: "Pagar {monto} USDC",
    inviteCodeTitle: "Crear un código de invitación",
    inviteCodeDetail: "Cualquier persona con el código puede unirse a este evento durante 7 días. Compártelo solo con quien confías.",
    inviteCodeAction: "Crear código",
    inviteEmailTitle: "Invitar por correo",
    inviteEmailDetail: "Solo {email} puede usar esta invitación. Sirve una vez y vence en 7 días.",
    inviteEmailAction: "Enviar invitación",
    accessNote: "Las personas que invites se unen como voluntarias y solo ven las tareas que les asignes.",
  },
  tema: {
    light: "Cambiar a tema claro",
    dark: "Cambiar a tema oscuro",
  },
  comunes: {
    loading: "Cargando…",
    tryAgain: "Intentar de nuevo",
    sample: "Ejemplo",
    event: "Evento",
    all: "Todas",
    amount: "Monto",
    date: "Fecha",
    unassigned: "Sin asignar",
    done: "Listo",
    now: "Ahora",
    later: "Después",
  },
  eventos: {
    title: "Eventos",
    create: "+ Crear",
    joinCode: "Unirme con un código",
    noLoad: "No pudimos cargar los eventos.",
    empty: "Todavía no hay eventos.",
    emptyHelp: "Crea uno o únete con un código.",
    member: "Integrante",
    organizer: "Organizador",
    team: "Equipo",
    volunteer: "Voluntario",
    toReview: "{n} por revisar",
    inReview: "{n} en revisión",
    invite: "Invitar",
    inviteRegion: "Invitar",
    closeInvite: "Cerrar",
    createCode: "Crear un código",
    email: "Correo",
    inviteEmail: "Invitar por correo",
    copyLink: "Copiar enlace",
    copied: "Copiado",
    inviteFail: "No pudimos crear la invitación.",
    tablist: "Evento",
    inbox: "Bandeja",
    tasks: "Tareas",
    report: "Informe",
    noTasks: "Todavía no hay tareas.",
    assignedLater: "Cuando quien organiza te asigne una tarea, aparece aquí.",
    joinTitle: "Unirme con un código",
    code: "Código",
    join: "Unirme",
    joinInvalid: "Ese código no sirve.",
    assign: "Asignar",
    assignFail: "No pudimos asignar esa tarea.",
    createTitle: "Crear evento",
    newEvent: "Evento nuevo",
    name: "Nombre",
    taskN: "Tarea {n}",
    titleLabel: "Título",
    type: "Tipo",
    amount: "Monto (USDC)",
    photoMust: "La foto tiene que mostrar",
    assignee: "Asignar a",
    remove: "Quitar {name}",
    taskWord: "tarea",
    addTask: "Agregar tarea",
    budget: "Presupuesto",
    workTasks: "Tareas de trabajo",
    reimbursements: "Reembolsos",
    total: "Total",
    createEvent: "Crear evento",
    needFields: "Escribe un nombre y al menos una tarea con monto.",
    createFail: "No pudimos crear el evento.",
    demoCreate: "El modo demo no puede crear eventos. Entra con tu correo para crear uno.",
    reportLead: "El presupuesto comparado con lo pagado. Cada tarea es un pago.",
    print: "Imprimir",
    against: "Presupuesto y gasto",
    paidLine: "Pagado {paid} · Restante {pending} · {n} voluntario",
    paidLineMany: "Pagado {paid} · Restante {pending} · {n} voluntarios",
    detail: "Detalle",
    limit: "Límite {amount}",
    upTo: "Hasta {amount}",
    credential: "Credencial",
    sampleReport: "Informe de ejemplo, hasta que carguen las tareas reales. Una tarea pagada puede incluir el enlace de la cadena.",
    accountsTitle: "Cuentas y billetera",
    accountsLead: "Una persona organiza y tres son voluntarias. Cada quien confirma el código que le llega por correo. Después su cuenta puede recibir el pago del evento.",
    accountDetails: "Datos de la cuenta",
    notSetUp: "Todavía no está lista",
    readyReceive: "Lista para recibir el pago",
    notReadyReceive: "No está lista para recibir el pago",
    confirm: "Confirmar",
    preparing: "Preparando…",
    prepareAccounts: "Preparar cuentas",
    accountsReady: "Cuentas listas",
    prepareFail: "No pudimos preparar la cuenta.",
    codeLabel: "Código",
    codeFor: "Código para {name}",
    limitUsdc: "Límite (USDC)",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    saveFail: "No se pudo guardar esa tarea.",
    editOnly: "Solo quien organiza puede editar las tareas.",
    editPhoto: "Esta tarea ya tiene una foto, así que no se puede editar.",
    editPaid: "Esta tarea ya tiene un pago, así que no se puede editar.",
    editLocked: "El monto ya está bloqueado en el pago, así que esta tarea no se puede editar.",
    needTitle: "Escribe un título.",
    titleLong: "El título es muy largo.",
    needPhoto: "Escribe lo que tiene que mostrar la foto.",
    noteLong: "Esa nota es muy larga.",
    noCap: "Las tareas de trabajo no tienen un límite.",
    choosePerson: "Elige a alguien de este evento.",
    nothingSave: "No hay nada que guardar.",
    notInEvent: "Esa persona no está en este evento.",
  },
  bienvenida: {
    kicker: "Bienvenida",
    title: "Ya entraste.",
    body: "Hyto es un mercado de tareas cortas. Haz el trabajo, envía una foto y cobra en dólares digitales (USDC).",
    step: "Da tu primer paso",
  },
  landing: {
    esloganAntes: "Demuestra tu valor,",
    esloganAcento: "recibe tu pago.",
    sub: "Haces tareas de proyectos reales, mandas una foto y te pagan en USDC.",
    legal: "El ingreso es con Cavos · tu billetera de Stellar se crea sola.",
    panel: "Cómo funciona Hyto",
    panelQ: "Bloquea el presupuesto. Revisa la foto. Paga el hito.",
    panelS: "Quien organiza revisa y aprueba desde una sola bandeja. Mile, el revisor con IA, lee cada foto; las personas deciden cada pago.",
    voluntarios: "Voluntarios",
    organizadores: "Organizadores",
    escrow: "Pago con depósito en Stellar",
  },
  entrar: {
    signIn: "Entrar",
    signUp: "Crear cuenta",
    newHere: "Nuevo en Hyto",
    welcomeBack: "Hola de nuevo",
    signUpBody: "Es tu primera vez. Creamos tu cuenta de Hyto y la dejamos lista para recibir pagos.",
    signInBody: "Ya tienes cuenta. Entra con Google o con un código que te mandamos al correo. No creamos otra cuenta.",
    signedIn: "Sesión iniciada",
    accountDetails: "Datos de la cuenta",
    dialog: "Entrar",
    dialogSignUp: "Crear cuenta",
    title: "Entra a Hyto",
    titleSignUp: "Crea tu cuenta en Hyto",
    close: "Cerrar",
    intro: "Con tu cuenta de Google o con un código que te mandamos al correo.",
    introSignUp: "Usa Google o tu correo. Creamos tu cuenta y la dejamos lista para tus pagos.",
    googleSignUp: "Crear cuenta con Google",
    emailSignUp: "Crear cuenta con correo",
    back: "Volver",
    createAccount: "Crear cuenta",
    creatingAccount: "Creando cuenta…",
    settingUp: "Preparando tu cuenta…",
    altaPendiente: "Abre Eventos y toca Preparar el cobro para terminar de preparar tu cuenta.",
    openEvents: "Abrir Eventos",
    emailCode: "Te enviamos un código por correo. No necesitas otra aplicación.",
    email: "Correo",
    sending: "Enviando…",
    sendCode: "Enviar código",
    or: "o",
    openingGoogle: "Abriendo Google…",
    openingApple: "Abriendo Apple…",
    google: "Entrar con Google",
    code: "Código",
    signingIn: "Entrando…",
    resend: "Reenviar código",
    tryDemo: "Probar el modo demo",
    noAccount: "No necesitas una cuenta",
    demoRole: "Rol de la sesión demo",
    organizerDemo: "Cuenta demo de organizador",
    volunteerDemo: "Cuenta demo de voluntario",
    enterDemo: "Entrar como demo",
    legal: "El ingreso es con Cavos. Entrar abre la cuenta que ya tienes.",
    legalSignUp: "El ingreso es con Cavos. Se crea una cuenta para guardar tu pago.",
    switching: "Cambiando…",
    switchVolunteer: "Cambiar a la cuenta demo de voluntario",
    switchOrganizer: "Cambiar a la cuenta demo de organizador",
    leaving: "Saliendo…",
    leaveDemo: "Salir del demo",
    demoMode: "Modo demo",
    signInAgain: "Vuelve a entrar",
    espera: "Espera {n} s antes de pedir otro código",
    couldNotSignIn: "No se pudo entrar.",
    leaveDemoFail: "No se pudo salir del demo.",
    demoOpenFail: "No se pudo abrir el demo. Inténtalo de nuevo.",
    sub: "Haces tareas de proyectos reales, mandas una foto y te pagan en USDC. Mile revisa la prueba; una persona aprueba cada pago.",
    chipEnviando: "Mile está buscando…",
    chipCodigo: "Tu código va en camino",
    chipError: "Algo no cuadró",
    chipExito: "¡Listo!",
    pestanas: "Entrar o crear una cuenta",
    paso: "Paso {n} de 3",
    pasoCorreo: "Correo",
    pasoCodigo: "Código",
    pasoListo: "Listo",
    googleContinuar: "Continuar con Google",
    appleContinuar: "Continuar con Apple",
    oCorreo: "o con tu correo",
    correoEjemplo: "tu@correo.com",
    ayudaCorreo: "Te enviamos un código de 6 dígitos. Revisa también el spam.",
    continuarCorreo: "Continuar con correo",
    enviandoCodigo: "Enviando código…",
    cambiarCorreo: "Cambiar correo",
    revisaCorreo: "Revisa tu correo",
    enviamosA: "Enviamos un código de 6 dígitos a",
    digito: "Dígito {n} de 6",
    autoConfirma: "Se confirma solo al escribir el último dígito.",
    noLlego: "¿No te llegó?",
    reenviarEn: "Reenviar código en {t}",
    pedirOtro: "Pedir otro código",
    usarOtro: "Usar otro correo",
    irCrearCuenta: "Crear una cuenta",
    probarOtraVez: "Probar otra vez",
    codigoMalTitulo: "Ese código no coincide.",
    codigoMalCuerpo: "Revisa tu correo e intenta de nuevo.",
    codigoVencidoTitulo: "Ese código venció.",
    codigoVencidoCuerpo: "Pide otro y te lo mandamos al mismo correo.",
    yaEntraste: "Ya entraste.",
    llevando: "Sesión iniciada. Te estamos llevando…",
    irTareas: "Continuar",
    soloMirar: "¿Solo quieres mirar?",
    probarDemo: "Probar el demo",
    ayudaEnlace: "Te enviamos un enlace para entrar. Revisa también el spam.",
    enviandoEnlace: "Enviando enlace…",
    chipEnlace: "Tu enlace va en camino",
    pasoEnlace: "Enlace",
    enviamosEnlace: "Enviamos un enlace para entrar a",
    abrirEnlace: "Ábrelo en este navegador para terminar. Después puedes cerrar esta pestaña.",
    reenviarEnlace: "Reenviar enlace",
    reenviarEnlaceEn: "Reenviar enlace en {t}",
    mile: {
      dive: "Mile está buscando tu código…",
      code: "Mile trajo tu código.",
      worry: "Mile no pudo usar ese código.",
      win: "Mile lo encontró. Ya entraste.",
    },
  },
  tareas: {
    title: "Mis tareas",
    earned: "Ganado",
    inReview: "En revisión",
    toDo: "Por hacer",
    one: "tarea",
    many: "tareas",
    loading: "Cargando tareas…",
    emptyTitle: "Aún no tienes tareas",
    emptyBody: "Únete a un evento con el código que te dio el organizador y tus tareas aparecen aquí.",
    join: "Unirme con código",
    viewEvents: "Ver eventos",
    hello: "¡Hola, {name}!",
    helloNoName: "¡Hola!",
    youHave: "Tienes {n} tareas por hacer.",
    youHaveOne: "Tienes 1 tarea por hacer.",
    allDone: "Estás al día. Mile te avisa si llega algo nuevo.",
    filterAll: "Todas",
    filterPending: "Pendientes",
    filterSent: "Enviadas",
    filterDone: "Hechas",
    badgePending: "Pendiente",
    badgeSent: "Enviada",
    badgePaid: "Pagada",
    badgeRejected: "Rechazada",
    takeAnotherPhoto: "Tomar otra foto",
    chooseAnotherFile: "Elegir otro archivo",
    mileChecks: "Mile revisa {n} puntos de tu foto antes de enviarla al organizador.",
    mileChecksOne: "Mile revisa tu foto antes de enviarla al organizador.",
    mileReviewing: "Mile está revisando tu foto",
    paidNote: "Pagada · {amount} en tu billetera",
    due: "Vence {when}",
    loadingMile: "Mile está trayendo tus tareas…",
    eventsCount: "{n} eventos",
    earnedUsdc: "{amount} ganados",
    inReviewShort: "en revisión",
    toDoShort: "por hacer",
    sortMenu: "Ordenar",
    uploadEvidence: "Subir evidencia",
    howItWorks: "Cómo funciona",
    step1: "Te unes al evento con el código del organizador.",
    step2: "Haces la tarea y subes una foto.",
    step3: "Mile la revisa, el organizador aprueba y te pagan en USDC.",
    emptyPendingTitle: "No tienes tareas pendientes. ¡Todo enviado!",
    emptyPendingAction: "Ver enviadas",
    emptySentTitle: "No hay fotos esperando revisión.",
    emptySentAction: "Ver pendientes",
    emptyDoneTitle: "Todavía no te han pagado ninguna tarea. Cuando el organizador apruebe una foto, aparece aquí.",
    emptyDoneAction: "Ver pendientes",
    hideWelcome: "Ocultar",
    filter: "Filtrar tareas",
    sort: "Ordenar tareas",
    sortLabel: "Orden",
    sortPriority: "Prioridad",
    sortDefault: "Por defecto",
    sortHighest: "Mayor pago",
    bestPaid: "Mejor pago",
    upTo: "Hasta {monto}",
    openCamera: "Abrir cámara",
    view: "Ver tarea",
  },
  evidencia: {
    back: "Volver a Mis tareas",
    sentAction: "Evidencia enviada, hay que corregir algo",
    sent: "Evidencia enviada",
    upload: "Subir evidencia",
    tabs: "Qué vas a enviar",
    tabReceipt: "Recibo",
    tabTask: "Tarea",
    mismatchReceipt: "Esta tarea pide una foto con la cámara. Vuelve a la pestaña Tarea.",
    mismatchTask: "Esta tarea pide un recibo en PDF o imagen. Vuelve a la pestaña Recibo.",
    backToTask: "Volver a Tarea",
    backToReceipt: "Volver a Recibo",
    receiptHelp: "Sube el comprobante o la factura en PDF o en imagen. Quien organiza lo revisa y envía el pago.",
    photoHelp: "Toma la foto del trabajo terminado con la cámara. Quien organiza lo revisa y envía el pago.",
    fileSent: "Archivo enviado",
    photoSent: "Foto enviada",
    uploaded: "Foto subida correctamente",
    reachedOrganizer: "Tu foto ya le llegó al organizador",
    fixSuffix: " Quien organiza no puede enviar el pago hasta que esto se corrija.",
    organizerNow: "Quien organiza ya puede revisarla. Esta tarea se muestra como Pagada cuando envíen el dinero.",
    organizerApproves: "El organizador aprueba y luego te pagan.",
    organizerCall: "Quien organiza toma la decisión final",
    anotherMaybe: "Si la foto no se ve bien, pueden pedirte otra.",
    invoicePdf: "PDF de la factura",
    alt: "Evidencia",
    camera: "Vista de la cámara",
    receiptPlaceholder: "PDF o imagen del comprobante",
    workPlaceholder: "Foto del trabajo",
    choosePdf: "Elegir un PDF o una imagen",
    gallery: "Toma la foto ahora. No se aceptan fotos de la galería.",
    mustShow: "Tu foto debe mostrar",
    takePhoto: "Tomar foto",
    send: "Enviar evidencia",
    sending: "Enviando…",
    chooseFile: "Elegir un archivo",
    openCamera: "Abrir cámara",
    sendingNote: "Enviando la foto. La recomendación puede tardar unos segundos.",
    chooseAnother: "Elegir otro archivo",
    takeAnother: "Tomar otra",
    sendAnother: "Enviar otro archivo",
    sample: "Tarea de ejemplo, hasta que carguen las tuyas.",
    noCameraShow: "No se pudo mostrar la cámara.",
    noCamera: "No se pudo abrir la cámara. Permite la cámara e intenta de nuevo.",
    cameraNotReady: "La cámara todavía no está lista.",
    noPhoto: "No se pudo tomar la foto.",
    badFile: "Elige un PDF, JPEG, PNG o WebP.",
    useCamera: "Toma la foto con la cámara.",
    noSend: "No se pudo enviar. Intenta de nuevo.",
    sendFailed: "No se pudo enviar. Revisa tu conexión e intenta de nuevo.",
    sendUnconfirmed: "El servidor no confirmó el envío. Intenta de nuevo.",
    sendUnknown: "La conexión se cortó antes de que Hyto confirmara el envío. Abre Mis tareas para revisar antes de enviarlo otra vez.",
    noTask: "No encontramos esa tarea.",
    mileHi: "HOLA, SOY MILE",
    mileCheck: "Antes de enviarla, yo reviso tu foto",
    mileWhy: "Así llega completa al organizador y te pagan más rápido.",
    cameraOff: "Cámara apagada. Actívala para tomar la foto.",
    galleryHint: "Tómala ahora con la cámara: no se aceptan fotos viejas de la galería.",
    onePhoto: "1 foto",
    sendEvidence: "Enviar evidencia",
    takePhotoFirst: "Primero toma la foto",
    chooseFirst: "Primero elige tu foto",
    checking: "Revisando",
    mileChecking: "Mile está revisando tu foto",
    fewSeconds: "Tarda unos segundos. Puedes esperar aquí.",
    sentShort: "Enviada",
    willTell: "Te avisamos cuando el organizador decida.",
    greatJob: "¡Buen trabajo! Tu foto llegó",
    greatJobName: "¡Buen trabajo, {name}! Tu foto llegó",
    greatJobSub: "Te avisamos apenas el organizador la apruebe.",
    sentAt: "{event} · enviada {time}",
    whatNow: "Qué pasa ahora",
    stepMile: "Mile revisa tu foto",
    stepOrganizer: "El organizador aprueba",
    stepPay: "Te pagan",
    stepPayAmount: "{amount} a tu billetera",
    now: "Ahora",
    backToTasks: "Volver a mis tareas",
    taskRejected: "Tarea rechazada",
    missingPoint: "Falta: {point}",
    organizerAsked: "El organizador pidió otra foto",
    retakeFrame: "Toma otra foto con todo lo que se pide dentro del cuadro.",
    restFine: "Lo demás ya está bien.",
    howPhoto: "Así quedó tu foto",
    notInPhoto: "No aparece en la foto",
    organizerRole: "{name} · organizador",
    sendUntil: "Puedes enviarla hasta {when}",
    deadlineClosed: "Se cerró el plazo de esta tarea",
    deadlineTalk: "Habla con el organizador si necesitas más tiempo.",
    askedAnother: "Pidió otra foto",
    attempt: "Intento {n}",
    youDidIt: "¡Lo lograste! {name} aprobó tu foto.",
    youDidItNoName: "¡Lo lograste! Aprobaron tu foto.",
    youGotPaid: "Te pagaron",
    paidFor: "Por «{title}». Ya está en tu billetera.",
    taskPayment: "Pago de la tarea",
    youReceived: "Recibiste",
    viewReceipt: "Ver comprobante",
    viewWallet: "Ver mi billetera",
    keepGoing: "Seguir con mis tareas",
    stepOrganizerName: "El organizador aprueba ({name} decide)",
    photoSentAt: "Foto enviada · {time}",
    useCameraShort: "Usar cámara",
    closePaid: "Cerrar",
  },
  bandeja: {
    inbox: "Bandeja",
    none: "Todavía no hay envíos.",
    oneWaiting: "{n} envío esperando tu revisión",
    manyWaiting: "{n} envíos esperando tu revisión",
    backExample: "Volver al ejemplo de ZEEK",
    filter: "Filtrar envíos",
    nothingApprove: "Nada por aprobar",
    whenPhoto: "Cuando alguien envía una foto, aparece aquí.",
    invite: "Invitar",
    create: "Crear evento",
    nothingView: "Nada en esta vista.",
    assign: "Asignar",
    review: "Revisar",
    recommendation: "Recomendación",
    noRecommendation: "Todavía no hay recomendación",
    photoMust: "La foto tiene que mostrar",
    mileSuggests: "Mile solo sugiere. Tú apruebas cada pago.",
    openReview: "Abrir la revisión",
    sample: "Evento de ejemplo, hasta que carguen las tareas reales.",
    updated: "Actualizado ahora",
    retry: "Reintentar la revisión",
    retrying: "Reintentando…",
    retryFail: "No se pudo reintentar la revisión.",
  },
  numeros: {
    budget: "Presupuesto",
    paid: "Pagado",
    pending: "Restante",
  },
  revision: {
    crumb: "Revisión de la evidencia",
    openInvoice: "Abrir la factura",
    sampleEvidence: "Evidencia de ejemplo",
    noPhoto: "Todavía no hay foto",
    waitingVolunteer: "Esperando a que la persona voluntaria envíe una.",
    steps: "Pasos del pago",
    sampleReview: "Revisión de ejemplo. La marca de pagado se queda en este dispositivo.",
    mileNo: "Mile no está disponible. No hay puntaje de IA para esta foto.",
    amountReceipt: "Monto en el comprobante",
    notShown: "No aparece",
    printedConverted: "Impreso {monto}, convertido a {tasa} {moneda} por dólar.",
    printedNotConverted: "Impreso {monto}. No tiene una moneda que Hyto pueda convertir, así que no se pasó a dólares.",
    printedDate: "Impreso {fecha}, que no se pudo leer como fecha.",
    amountToPay: "Monto a pagar",
    upTo: "Hasta {monto}. Confirma este monto antes de desplegar.",
    amountConfirmed: "Monto confirmado",
    confirming: "Confirmando…",
    confirmAmount: "Confirmar monto",
    setsAside: "Esto aparta {monto} para esta tarea. Lo confirmas una vez.",
    oneMore: "El presupuesto ya está listo. Una confirmación más bloquea el dinero.",
    secured: "Presupuesto asegurado. El pago envía {monto}.",
    paymentSent: "Pago enviado. Esperamos a que la red lo muestre como liberado. No pagues otra vez.",
    checkingBudget: "Estamos revisando el presupuesto bloqueado en la red. Actualiza en unos segundos si no aparece nada.",
    paymentStillPending: "Pago enviado. La red todavía no lo muestra como liberado. No pagues otra vez.",
    budgetUnread: "Todavía no pudimos leer el presupuesto bloqueado. Bloquear y pagar siguen apagados hasta poder leerlo, para que nada se ejecute dos veces.",
    technical: "Detalles técnicos",
    yourAccount: "Tu cuenta {direccion}",
    budgetRef: "Referencia del presupuesto {direccion}",
    paidAmount: "Pagado {monto}",
    paidWait: "Pagado. El enlace de la cadena aparece cuando la red lo confirma.",
    samplePay: "Esto es un ejemplo. Un pago real agrega un enlace a la cadena.",
    credential: "Credencial",
    approve: "Aprobar",
    askAnother: "Pedir otra foto",
    whatsMissing: "¿Qué falta?",
    messageFor: "Mensaje para {name} (opcional)",
    cancelAsk: "Cancelar",
    backEvent: "Volver al evento",
    photoBroken: "No se pudo mostrar esta foto.",
    loadingPhoto: "Cargando la foto",
    noLoad: "No se pudo cargar esta revisión.",
    noAsk: "No se pudo pedir otra foto.",
    manual: "Necesita una revisión manual",
    copia: "Esta foto coincide con un envío anterior, así que la recomendación se queda en insuficiente.",
    origenIa: "Recomendación de la IA",
    origenMuestra: "Recomendación de ejemplo",
    origenFallo: "La revisión falló",
  },
  cuenta: {
    titulo: "Cuenta",
    signOut: "Salir",
    signingOut: "Saliendo…",
    noLoad: "No pudimos cargar tu cuenta.",
    loading: "Cargando la cuenta",
    demoNota: "Ejemplo del demo. Estas tareas y montos no son pagos en la red.",
    demoNotaMuestra: " La dirección y el saldo también son de ejemplo.",
    demoNotaSesion: " La billetera es la de esta sesión.",
    wallet: "Billetera",
    signInWallet: "Entra con una billetera para ver tu dirección pública.",
    testnetUsdc: "USDC",
    sampleBalance: "Saldo de ejemplo",
    onWallet: "En esta billetera ahora",
    ausente: "Esta billetera todavía no está en la red de prueba. Abre Eventos y toca Preparar el cobro.",
    noBalance: "No pudimos leer el saldo.",
    addWallet: "Agrega una billetera para ver tu USDC.",
    copy: "Copiar dirección",
    copied: "Copiado",
    viewTestnet: "Ver en el explorador",
    copyHere: "Cópiala desde aquí. Esta es la dirección pública.",
    thisMonth: "Este mes",
    lastMonth: "Mes pasado",
    allTime: "Total",
    earnedEvents: "Ganado en eventos",
    earningsByMonth: "Ingresos por mes",
    sinFecha: "Algunos pagos no tienen fecha guardada, así que solo cuentan en el total.",
    vacio: "Las tareas pagadas aparecen aquí, mes por mes.",
    vacioConPagos: "Las tareas completadas están aquí. Un mes aparece cuando un pago tiene fecha.",
    tasksPaid: "Tareas pagadas",
    noneYet: "Todavía ninguna",
    milestonesReleased: "Hitos liberados",
    projectsFinished: "Proyectos terminados",
    allTasksPaid: "Todas tus tareas pagadas",
    streak: "Racha",
    oneMonth: "1 mes",
    months: "{n} meses",
    inARow: "Seguidos",
    noPayoutMonth: "Todavía no hay un mes con pago",
    bestMonth: "Mejor mes",
    bestLater: "Aparece después de un pago",
    milestones: "Hitos",
    earned: "Ganado",
    locked: "Bloqueado",
    recent: "Tareas pagadas recientes",
    nothingPaid: "Todavía no hay pagos. Termina una tarea y aparece aquí.",
    insigniaPrimera: "Primera tarea",
    insigniaPrimeraDetalle: "Una tarea pagada",
    insigniaCinco: "Cinco tareas",
    insigniaCincoDetalle: "Cinco tareas pagadas",
    insigniaDiez: "Diez tareas",
    insigniaDiezDetalle: "Diez tareas pagadas",
    insigniaProyecto: "Primer proyecto",
    insigniaProyectoDetalle: "Todas las tareas de un proyecto pagadas",
    insigniaTres: "Tres proyectos",
    insigniaTresDetalle: "Tres proyectos terminados",
    insigniaRacha: "Racha de tres meses",
    insigniaRachaDetalle: "Ingresos tres meses seguidos",
    confirmWindow: "Confirma en la ventana si te lo pide. Puede tardar un minuto.",
    newAccount: "Si esta cuenta es nueva, primero la abrimos en la red de prueba. Confirmas una vez para que pueda recibir el pago del evento.",
    pasaporteTitulo: "Stellar Passport",
    pasaporteDetalle: "Registra la participación y los logros en el ecosistema Stellar.",
    pasaporteAbrir: "Abrir Stellar Passport",
    passkeyTitulo: "Usa Hyto en otros dispositivos",
    passkeyDetalle:
      "La clave de tu cuenta está guardada en este navegador. Agrega una llave de acceso para que tu teléfono u otra computadora también puedan abrirla. Guárdala donde guardas tus contraseñas. Funciona como una llave de tu cuenta, así que no la compartas.",
    passkeyAgregar: "Agregar llave de acceso",
    passkeyAgregando: "Agregando…",
    passkeyListo: "Llave de acceso agregada. En otro dispositivo, entra a Hyto y elige Use passkey cuando lo pida.",
    passkeyAviso: "Agrega una llave de acceso en Cuenta para usar Hyto en tus otros dispositivos.",
  },
  estados: {
    pendiente: "Pendiente",
    revision: "En revisión",
    pagado: "Pagado",
  },
  veredictos: {
    cumplio: "Completado",
    parcial: "Parcialmente completado",
    insuficiente: "Insuficiente",
  },
  tipos: {
    trabajo: "Trabajo",
    reembolso: "Reembolso",
  },
  choices: {
    stand: "puesto",
    factura: "factura",
    trabajo: "trabajo",
    otra: "otra",
  },
  clasificacion: {
    priority: "Prioridad",
    difficulty: "Dificultad",
    normal: "Normal",
    high: "Alta",
    highPriority: "Prioridad alta",
    notSet: "Sin definir",
    easy: "Fácil",
    medium: "Media",
    hard: "Difícil",
    saveFail: "No se pudo guardar la prioridad y la dificultad.",
    onlyOrganizer: "Solo el organizador puede definir la prioridad y la dificultad.",
    choosePriority: "Elige Normal o Alta.",
    chooseDifficulty: "Elige Fácil, Media, Difícil o Sin definir.",
  },
  legado: {
    met: "cumplida",
    notMet: "no cumplida",
    category: " Categoría {choice}, condición {condicion}, evidencia {evidencia}.",
  },
  pago: {
    lockBudget: "Bloquear presupuesto",
    finishLocking: "Terminar de bloquear",
    settingUp: "Preparando…",
    locking: "Bloqueando…",
    approvePay: "Aprobar y pagar",
    checking: "Revisando…",
    approving: "Aprobando…",
    paying: "Pagando…",
    viewChain: "Ver en la cadena",
    checkAgain: "Revisar otra vez",
    preparePayout: "Preparar el cobro",
    preparingPayout: "Preparando…",
    payoutReady: "Listo para cobrar",
    payoutDone: "Cuenta de cobro lista",
    checkingPayout: "Revisando tu cuenta de cobro…",
    saveProject: "Guardar proyecto",
    reviewPhoto: "Revisar la foto",
    pay: "Pagar",
    budgetNotLocked: "Presupuesto sin bloquear",
    paymentFailed: "El pago falló",
    noUsdcLeft: "No salió USDC del depósito.",
    settingUpLong: "Preparando el presupuesto. Deja esta página abierta. Puede tardar un minuto.",
    lockingLong: "Bloqueando el presupuesto. Confirma en la ventana si te lo pide. Puede tardar un minuto.",
    recording: "Anotando que el trabajo está listo.",
    approvingLong: "Aprobando el pago.",
    sending: "Enviando el pago. Deja esta página abierta.",
  },
  errores: {
    paso: "Ese paso no se completó. Intenta de nuevo.",
    noInicio: "No pudimos empezar ese paso. Intenta de nuevo.",
    noCompleto: "No pudimos completar ese paso. Intenta de nuevo.",
    noPresupuesto: "No pudimos revisar el presupuesto. Intenta de nuevo.",
    noCobroFin: "No pudimos terminar de preparar el cobro. Intenta de nuevo.",
    noCobroCheck: "No pudimos revisar si esta cuenta puede recibir el pago. Intenta de nuevo.",
    noCobroListo: "No pudimos dejar esta cuenta lista para recibir el pago. Intenta de nuevo.",
    noCobroConfirm: "No pudimos confirmar la preparación del cobro. Intenta de nuevo.",
    noCuentaPago: "No pudimos revisar la cuenta de cobro. Intenta de nuevo.",
    dispositivo:
      "Este navegador todavía no tiene la clave de tu cuenta. Abre Hyto una vez en el navegador donde creaste tu cuenta, ve a Cuenta y toca Agregar llave de acceso. Luego vuelve a intentarlo aquí y usa esa llave.",
    passkey: "Confirma con tu llave de acceso para usar tu cuenta en este navegador. Intenta de nuevo y elige Use passkey cuando lo pida.",
    passkeySinSoporte: "Este navegador no puede crear llaves de acceso. Prueba con una versión reciente de Chrome, Safari o Edge.",
    passkeySinClave:
      "Este navegador no tiene la clave de tu cuenta, así que no puede agregar una llave de acceso. Abre Hyto en el navegador donde creaste tu cuenta y agrégala ahí.",
    passkeyCancelada: "Cancelaste. No se agregó ninguna llave de acceso.",
    passkeyFallo: "No pudimos agregar la llave de acceso. Intenta de nuevo.",
    cobroSinXlm: "Esta cuenta de cobro no tiene XLM de prueba para la comisión de la red. Intenta de nuevo en unos minutos o avísale a quien administra Hyto.",
    cobroSecuencia: "La cuenta de cobro cambió mientras se preparaba. Intenta de nuevo.",
    cobroFirmante: "Este ingreso no puede confirmar por esta cuenta de cobro. Vuelve a entrar e intenta de nuevo.",
    cobroVencido: "La confirmación venció antes de llegar a la red. Intenta de nuevo.",
    cobroPendiente: "La red todavía no confirma la preparación del cobro. Espera un momento e intenta de nuevo.",
    cobroOtraCuenta: "Este ingreso abrió una cuenta de cobro distinta de la que Hyto tiene para ti. Vuelve a entrar e intenta de nuevo.",
    cobroLento: "La confirmación tardó demasiado. Revisa tu conexión e intenta de nuevo.",
    entrarOtraVez: "Vuelve a entrar antes de continuar.",
    entrarContinuar: "Entra para continuar.",
    noTestnet: "Esta cuenta todavía no está en la red de prueba. Abre Eventos y toca Preparar el cobro.",
    noPareceCuenta: "Eso no parece una cuenta de cobro. Vuelve a entrar.",
    noCoincideIngreso: "Esa cuenta no coincide con este ingreso. Vuelve a entrar.",
    confirmacionNoCoincide: "La confirmación no coincidió con este ingreso. Vuelve a entrar e intenta de nuevo.",
    confirmacionNoLlego: "La confirmación no llegó. Intenta de nuevo.",
    confirmacionNoEnvio: "No se pudo enviar la confirmación. Intenta de nuevo.",
    confirmacionNoCuenta: "Esa confirmación no coincide con esta cuenta. Intenta de nuevo.",
    noPreparar: "No pudimos preparar ese paso. Intenta de nuevo.",
    bloquearAntes: "Bloquea el presupuesto antes de pagar.",
    presupuestoNoBloqueado: "El presupuesto no quedó bloqueado. Intenta Bloquear presupuesto otra vez.",
    yaBloqueado: "Esta tarea ya tiene el presupuesto bloqueado.",
    enviadoSinContrato: "El presupuesto se envió, pero todavía no pudimos confirmarlo. Actualiza en un momento.",
    sinWalletVoluntario: "Todavía no tenemos la cuenta de cobro de la persona voluntaria. Pídele que entre a Hyto y abra la tarea.",
    esperaRevision: "Espera a que termine la revisión de la foto antes de bloquear el presupuesto.",
    montoCero: "El monto tiene que ser mayor que cero.",
    soloOrganizador: "Solo quien organiza puede bloquear el presupuesto y pagar.",
    soloResolver: "Solo quien resuelve disputas puede hacer esto.",
    saldoRed: "Esta cuenta necesita un poco de saldo de prueba para la comisión de la red. Agrega un poco e intenta de nuevo.",
    cancelaste: "Cancelaste la confirmación. No se envió nada.",
    reingreso: "Tu ingreso venció. Vuelve a entrar para continuar.",
    sinConfig: "El ingreso todavía no está configurado.",
    cuentasNo: "La preparación de la cuenta todavía no está disponible.",
    cuentaNoAbrio: "La cuenta de cobro no se abrió. Intenta de nuevo.",
    demoCobro: "El modo demo no puede preparar cobros. Entra con tu correo para continuar.",
    demoPagos: "El modo demo no puede enviar pagos. Entra con tu correo para continuar.",
    servicioRechazo: "El servicio de pagos rechazó ese paso. Intenta de nuevo.",
    receptorNoListo: "La cuenta de cobro de la persona voluntaria todavía no está lista. Pídele que abra Eventos en Hyto y toque Preparar el cobro.",
    horizonReceptor: "No pudimos contactar la red para revisar la cuenta de cobro. Intenta de nuevo.",
    listoCobro: "Quien va a cobrar todavía no puede recibir el pago. Tiene que abrir Eventos y tocar Preparar el cobro.",
    faucetTestnet: "No pudimos abrir esta cuenta de cobro en la red de prueba. Abre Eventos y toca Preparar el cobro.",
    soloTestnet: "Las cuentas de cobro solo se abren en la red de prueba.",
    servidorIncompleto: "La configuración de pagos no está completa en el servidor. Avísale a quien administra Hyto.",
    pagosNoDisponibles: "Los pagos no están disponibles ahora. Avísale a quien administra Hyto.",
    yaPagada: "Esta tarea ya está pagada.",
    saldoInsuficiente: "Todavía no hay suficiente dinero apartado. Termina de bloquear el presupuesto y después paga.",
    codigoNo: "Ese código no coincide. Revisa tu correo e intenta de nuevo.",
    codigoVencio: "Ese código venció. Pide otro.",
    sinRed: "No hay conexión. Revisa la red e intenta de nuevo.",
    googleCerrado: "Cerraste la ventana de Google. Intenta de nuevo.",
    googleBloqueado: "El navegador bloqueó la ventana de Google. Permítela e intenta de nuevo.",
    correo: "Escribe un correo válido.",
    demoCorreo: "Ese correo de demo no recibe mensajes. Usa un correo real o entra con Google.",
    spam: "El código llega por correo. Revisa también el spam.",
    spamEnlace: "El enlace llega por correo. Revisa también el spam.",
    metodoRecuperacion: "Esta cuenta entra de otra forma. Usa la opción para entrar que aparece e inténtalo de nuevo.",
    sinRespaldo:
      "Todavía no se puede abrir esta cuenta en este navegador. Abre Hyto una vez en el navegador donde la creaste y luego vuelve a intentarlo aquí.",
    noEntrar: "No se pudo entrar. Intenta de nuevo.",
    sinCuenta: "No encontramos una cuenta de Hyto con este correo. Crea una primero.",
    montoInvalido: "Escribe un monto mayor que cero, con hasta dos decimales.",
    montoTope: "El monto no puede ser mayor que el límite.",
    montoTarde: "Este pago ya está preparado.",
  },
};

type Unir<T, P extends string = ""> = {
  [K in keyof T & string]: T[K] extends string ? `${P}${K}` : Unir<T[K], `${P}${K}.`>;
}[keyof T & string];

export type Clave = Unir<typeof en>;

export type FuenteTextos = {
  en: Rama<typeof en>;
  es: Rama<typeof en>;
};

export function rutas(valor: unknown, prefijo = ""): string[] {
  if (valor === null || typeof valor !== "object") return prefijo ? [prefijo] : [];
  const lista: string[] = [];
  for (const [clave, hijo] of Object.entries(valor as Record<string, unknown>)) {
    const ruta = prefijo ? `${prefijo}.${clave}` : clave;
    if (hijo !== null && typeof hijo === "object") lista.push(...rutas(hijo, ruta));
    else lista.push(ruta);
  }
  return lista;
}

function caminar(nodo: unknown, partes: string[]): unknown {
  let actual = nodo;
  for (const parte of partes) {
    if (!actual || typeof actual !== "object" || !(parte in actual)) return undefined;
    actual = (actual as Record<string, unknown>)[parte];
  }
  return actual;
}

export function leerTexto(idioma: Idioma, clave: string, fuente: FuenteTextos = { en, es }): string {
  const partes = clave.split(".");
  const propio = caminar(idioma === "es" ? fuente.es : fuente.en, partes);
  if (typeof propio === "string" && propio.length > 0) return propio;
  const ingles = caminar(fuente.en, partes);
  if (typeof ingles === "string" && ingles.length > 0) return ingles;
  return clave;
}

function aplicar(valor: string, vars?: Record<string, string | number>): string {
  if (!vars) return valor;
  return valor.replace(/\{(\w+)\}/g, (todo, nombre: string) => {
    const dato = vars[nombre];
    return dato === undefined ? todo : String(dato);
  });
}

export function texto(idioma: Idioma, clave: Clave, vars?: Record<string, string | number>): string {
  return aplicar(leerTexto(idioma, clave), vars);
}
