/**
 * Public landing speech for community accountability. `discurso` stays English so existing checks keep one source.
 * `discursoEs` is the Costa Rica Spanish twin. `discursoDe` picks one; English is the default.
 * Keys stay stable. Components read these strings; they do not invent sentences.
 * `ctaSignIn` matches the Sign in button rendered by Entrar.
 */

export const CLAVES_DISCURSO = [
  "sloganLead",
  "sloganPay",
  "subheadline",
  "networkLead",
  "networkBody",
  "ctaSignIn",
  "ctaCuenta",
  "ctaDemo",
  "ctaDemoHelp",
  "ctaDemoVolunteer",
  "ctaDemoOrganizer",
  "ctaDemoBusy",
  "ctaDemoError",
  "navComo",
  "navFaq",
  "navContacto",
  "navEquipo",
  "navCaso",
  "navApp",
  "navLegales",
  "navMenu",
  "stepsTitle",
  "step1Title",
  "step1Body",
  "step2Title",
  "step2Body",
  "step3Title",
  "step3Body",
  "audienceTitle",
  "workersTitle",
  "workersBody",
  "organizersTitle",
  "organizersBody",
  "trustTitle",
  "trustApproveTitle",
  "trustApproveBody",
  "trustAiTitle",
  "trustAiBody",
  "trustEscrowTitle",
  "trustEscrowBody",
  "legal",
  "mileKicker",
  "closeKicker",
  "closeTitle",
  "faqKicker",
  "faqTitle",
  "faqCryptoQuestion",
  "faqCryptoAnswer",
  "faqDollarsQuestion",
  "faqDollarsAnswer",
  "faqCostQuestion",
  "faqCostAnswer",
  "faqApproveQuestion",
  "faqApproveAnswer",
  "faqRejectQuestion",
  "faqRejectAnswer",
  "faqColonesQuestion",
  "faqColonesAnswer",
  "faqFundsQuestion",
  "faqFundsAnswer",
  "casoKicker",
  "casoTitle",
  "casoBodyPendiente",
  "casoBodyListo",
  "casoEnlace",
  "equipoKicker",
  "equipoTitle",
  "equipoLead",
  "contactoKicker",
  "contactoTitle",
  "contactoLead",
  "contactoNombre",
  "contactoCorreo",
  "contactoMensaje",
  "contactoEnviar",
  "contactoPromesa",
  "contactoCanal",
  "graciasTitle",
  "graciasLead",
  "graciasPaso",
  "graciasCta",
  "graciasFaq",
  "migasInicio",
  "migasFaq",
  "migasPrivacidad",
  "migasAria",
  "pieComo",
  "pieFaq",
  "pieContacto",
  "piePrivacidad",
  "pieApp",
  "pieTryhyto",
] as const;

export type ClaveDiscurso = (typeof CLAVES_DISCURSO)[number];

/** Meta, Open Graph, and Twitter description. The landing speech still names the asset; this line does not. */
export const DESCRIPCION_PAGINA =
  "Communities in Latin America funded from afar account for every spend. Lock digital dollars, send a photo of the work or the receipt, and a person releases the payment.";

export const discurso: Record<ClaveDiscurso, string> = {
  sloganLead: "Proof before",
  sloganPay: "payout.",
  subheadline:
    "Communities in Latin America funded from afar account for every spend. Lock digital dollars (USDC), send a photo of the work or the receipt, and a person releases the payment.",
  networkLead: "Practice network.",
  networkBody:
    "Digital dollars (USDC) here are for practice. Nothing on this network is real cash, and no live payment is recorded yet.",
  ctaSignIn: "Sign in",
  ctaCuenta: "Create a free account",
  ctaDemo: "Try the demo",
  ctaDemoHelp: "No account needed. Open a practice session as a volunteer or as an organizer.",
  ctaDemoVolunteer: "As a volunteer",
  ctaDemoOrganizer: "As an organizer",
  ctaDemoBusy: "Opening…",
  ctaDemoError: "Could not open the demo. Try again.",
  navComo: "How it works",
  navFaq: "FAQ",
  navContacto: "Contact",
  navEquipo: "Team",
  navCaso: "Practice payment",
  navApp: "Open the app",
  navLegales: "Legal pages",
  navMenu: "Page sections",
  stepsTitle: "How it works",
  step1Title: "Lock the funding",
  step1Body:
    "The funder sets each task amount aside in digital dollars (USDC) before the work starts. A stipend, a scholarship, or money to run an event, often sent by someone who is not there.",
  step2Title: "Send a photo",
  step2Body: "Photograph the work where it happened, or the receipt, including one in colones. That photo is the proof of the spend.",
  step3Title: "Release the payment",
  step3Body: "A person reviews the photo and releases the payment. Mile only recommends.",
  audienceTitle: "Who it is for",
  workersTitle: "Community members",
  workersBody: "Join the event, do the task assigned to you, and send the photo that accounts for the spend.",
  organizersTitle: "Organizers and funders",
  organizersBody: "The funder may be abroad. Lock the funding per task, review the proof, and release each payment. That record replaces loose screenshots and a spreadsheet.",
  trustTitle: "Why you can trust a payment",
  trustApproveTitle: "A person releases every payment",
  trustApproveBody: "Someone reviews the photo and decides. Hyto does not pay on its own.",
  trustAiTitle: "Mile only recommends",
  trustAiBody: "Mile reads the photo and suggests a score. Mile cannot sign or move the money.",
  trustEscrowTitle: "The money is set aside first",
  trustEscrowBody: "The organizer sets the task amount aside before the work, so the payment is waiting when the proof is approved.",
  legal: "Sign in with email through Cavos. An account is created to hold the payment. You do not need a separate cryptocurrency app.",
  mileKicker: "Meet Mile",
  closeKicker: "Start",
  closeTitle: "Ready to show the proof?",
  faqKicker: "Questions",
  faqTitle: "Before you start",
  faqCryptoQuestion: "Do I need to know about cryptocurrency?",
  faqCryptoAnswer: "No. Sign in with your email, do the task, and send a photo.",
  faqDollarsQuestion: "Why digital dollars, and not a local transfer?",
  faqDollarsAnswer:
    "The money comes from abroad in dollars, and the funder needs proof of the spend. Loose screenshots, a spreadsheet, or a local transfer such as SINPE do not leave a record anyone can check.",
  faqCostQuestion: "How much does Hyto cost?",
  faqCostAnswer:
    "Hyto's own fee is 0 today. When a payment is released, the hold that keeps the funds set aside may charge a 0.3 % protocol fee. When Hyto defines its own fee, that page will say the percentage before it applies.",
  faqApproveQuestion: "Who approves a payment?",
  faqApproveAnswer:
    "A person. The organizer of the event reviews the photo and decides. Mile only recommends a score. Mile does not sign or move money.",
  faqRejectQuestion: "What happens if the work is not approved?",
  faqRejectAnswer:
    "The payment is not released. The funds stay set aside for that task. There is no automatic return to the organizer's balance from the app today. A dispute can be opened so a resolver can split or return that amount.",
  faqColonesQuestion: "How do I convert digital dollars to colones?",
  faqColonesAnswer:
    "Hyto pays in digital dollars (USDC) on the practice network. Turning those into colones happens outside Hyto, through a service or bank that you choose. Hyto does not run that exchange.",
  faqFundsQuestion: "Does Hyto keep the funds?",
  faqFundsAnswer:
    "No. The funds for each task are set aside in a hold before the work starts. Hyto does not keep them. When a person approves, that amount is released to the member's account on the practice network.",
  casoKicker: "Practice payment",
  casoTitle: "First payment on the practice network",
  casoBodyPendiente:
    "There is no public practice payment receipt in this product yet. When the first one lands, this section will link to the public record. Until then, Hyto does not invent a payment or a made-up review.",
  casoBodyListo: "This is the first practice payment released through Hyto. Anyone can open the public receipt.",
  casoEnlace: "View the public receipt",
  equipoKicker: "Team",
  equipoTitle: "Who builds Hyto",
  equipoLead: "A small team in Costa Rica. Photos below are temporary initials until each person adds a portrait.",
  contactoKicker: "Contact",
  contactoTitle: "Write to us",
  contactoLead:
    "If you fund a community in Latin America, or you do the work on site, send a short message. We read every note.",
  contactoNombre: "Your name",
  contactoCorreo: "Your email",
  contactoMensaje: "Your message",
  contactoEnviar: "Send message",
  contactoPromesa: "We aim to reply within Josué confirma el tiempo.",
  contactoCanal: "Use this form. Do not send a personal email address to the public site.",
  graciasTitle: "Thank you. Your message was received.",
  graciasLead: "We will read it and reply. The response window is still the one Josué confirma el tiempo.",
  graciasPaso: "Next step while you wait",
  graciasCta: "Create a free practice account",
  graciasFaq: "Read the FAQ",
  migasInicio: "Home",
  migasFaq: "FAQ",
  migasPrivacidad: "Privacy",
  migasAria: "Breadcrumb",
  pieComo: "How it works",
  pieFaq: "FAQ",
  pieContacto: "Contact",
  piePrivacidad: "Privacy",
  pieApp: "Open the app",
  pieTryhyto: "Marketing site (tryhyto.com)",
};

export const discursoEs: Record<ClaveDiscurso, string> = {
  sloganLead: "Primero la prueba,",
  sloganPay: "después el pago.",
  subheadline:
    "Las comunidades en Latinoamérica que reciben fondos desde lejos rinden cuentas de cada gasto. Aparte dólares digitales (USDC), envíe una foto del trabajo o del recibo, y una persona libera el pago.",
  networkLead: "Red de práctica.",
  networkBody:
    "Los dólares digitales (USDC) aquí son para practicar. Nada en esta red es dinero real, y todavía no hay un pago en vivo registrado.",
  ctaSignIn: "Entrar",
  ctaCuenta: "Crear una cuenta gratis",
  ctaDemo: "Probar el demo",
  ctaDemoHelp: "No necesita una cuenta. Abra una sesión de práctica como voluntario o como organizador.",
  ctaDemoVolunteer: "Como voluntario",
  ctaDemoOrganizer: "Como organizador",
  ctaDemoBusy: "Abriendo…",
  ctaDemoError: "No se pudo abrir el demo. Inténtelo de nuevo.",
  navComo: "Cómo funciona",
  navFaq: "Preguntas",
  navContacto: "Contacto",
  navEquipo: "Equipo",
  navCaso: "Pago de práctica",
  navApp: "Abrir la app",
  navLegales: "Páginas legales",
  navMenu: "Secciones de la página",
  stepsTitle: "Cómo funciona",
  step1Title: "Aparte el financiamiento",
  step1Body:
    "Quien financia aparta el monto de cada tarea en dólares digitales (USDC) antes de que empiece el trabajo. Un estipendio, una beca o fondos para un evento, a menudo enviados por alguien que no está ahí.",
  step2Title: "Envíe una foto",
  step2Body: "Fotografíe el trabajo en el lugar, o el recibo, incluso si está en colones. Esa foto es la prueba del gasto.",
  step3Title: "Libere el pago",
  step3Body: "Una persona revisa la foto y libera el pago. Mile solo recomienda.",
  audienceTitle: "Para quién es",
  workersTitle: "Miembros de la comunidad",
  workersBody: "Únase al evento, haga la tarea que le asignaron y envíe la foto que comprueba el gasto.",
  organizersTitle: "Quienes organizan y financian",
  organizersBody: "Quien financia puede estar lejos. Aparte el financiamiento por tarea, revise la prueba y libere cada pago. Ese registro reemplaza las capturas sueltas y la hoja de cálculo.",
  trustTitle: "Por qué puede confiar en un pago",
  trustApproveTitle: "Una persona libera cada pago",
  trustApproveBody: "Alguien revisa la foto y decide. Hyto no paga solo.",
  trustAiTitle: "Mile solo recomienda",
  trustAiBody: "Mile lee la foto y sugiere una nota. No puede firmar ni mover el dinero.",
  trustEscrowTitle: "El dinero se aparta primero",
  trustEscrowBody:
    "Quien organiza aparta el monto de la tarea antes del trabajo, así el pago está esperando cuando se aprueba la prueba.",
  legal: "Usted entra con su correo por Cavos. Se crea una cuenta para guardar el pago. No necesita otra aplicación de criptomonedas.",
  mileKicker: "Conozca a Mile",
  closeKicker: "Empiece",
  closeTitle: "¿Listo para mostrar la prueba?",
  faqKicker: "Preguntas",
  faqTitle: "Antes de empezar",
  faqCryptoQuestion: "¿Necesito saber de criptomonedas?",
  faqCryptoAnswer: "No. Entre con su correo, haga la tarea y envíe una foto.",
  faqDollarsQuestion: "¿Por qué dólares digitales y no una transferencia local?",
  faqDollarsAnswer:
    "El dinero llega del extranjero en dólares, y quien financia pide prueba del gasto. Las capturas sueltas, una hoja de cálculo o una transferencia local como SINPE no dejan un registro que cualquiera pueda revisar.",
  faqCostQuestion: "¿Cuánto cuesta Hyto?",
  faqCostAnswer:
    "La comisión propia de Hyto hoy es 0. Al liberar un pago, el apartado que guarda los fondos puede cobrar una comisión de protocolo del 0,3 %. Cuando Hyto defina la suya, esa página dirá el porcentaje antes de que aplique.",
  faqApproveQuestion: "¿Quién aprueba un pago?",
  faqApproveAnswer:
    "Una persona. Quien organiza el evento revisa la foto y decide. Mile solo recomienda una nota. Mile no firma ni mueve dinero.",
  faqRejectQuestion: "¿Qué pasa si no se aprueba el trabajo?",
  faqRejectAnswer:
    "El pago no se libera. Los fondos siguen apartados para esa tarea. Hoy la app no tiene un botón que los devuelva al saldo de quien organiza. Se puede abrir una disputa para que quien resuelve reparta o devuelva ese monto.",
  faqColonesQuestion: "¿Cómo convierto dólares digitales a colones?",
  faqColonesAnswer:
    "Hyto paga en dólares digitales (USDC) en la red de práctica. Pasar eso a colones ocurre fuera de Hyto, con el servicio o el banco que usted elija. Hyto no hace ese cambio.",
  faqFundsQuestion: "¿Hyto guarda los fondos?",
  faqFundsAnswer:
    "No. Los fondos de cada tarea se apartan en un depósito antes de que empiece el trabajo. Hyto no los guarda. Cuando una persona aprueba, ese monto se libera a la cuenta del miembro en la red de práctica.",
  casoKicker: "Pago de práctica",
  casoTitle: "Primer pago en la red de práctica",
  casoBodyPendiente:
    "Todavía no hay un comprobante público de un pago de práctica en este producto. Cuando exista el primero, esta sección enlazará el registro público. Hasta entonces, Hyto no inventa un pago ni una reseña inventada.",
  casoBodyListo: "Este es el primer pago de práctica liberado con Hyto. Cualquiera puede abrir el comprobante público.",
  casoEnlace: "Ver el comprobante público",
  equipoKicker: "Equipo",
  equipoTitle: "Quién construye Hyto",
  equipoLead: "Un equipo pequeño en Costa Rica. Las fotos de abajo son iniciales temporales hasta que cada persona aporte un retrato.",
  contactoKicker: "Contacto",
  contactoTitle: "Escríbanos",
  contactoLead:
    "Si usted financia a una comunidad en Latinoamérica, o hace el trabajo en el lugar, envíe un mensaje breve. Leemos cada nota.",
  contactoNombre: "Su nombre",
  contactoCorreo: "Su correo",
  contactoMensaje: "Su mensaje",
  contactoEnviar: "Enviar mensaje",
  contactoPromesa: "Procuramos responder en Josué confirma el tiempo.",
  contactoCanal: "Use este formulario. No publique un correo personal en el sitio.",
  graciasTitle: "Gracias. Recibimos su mensaje.",
  graciasLead: "Lo leeremos y le responderemos. El plazo de respuesta sigue siendo el que Josué confirma el tiempo.",
  graciasPaso: "Siguiente paso mientras espera",
  graciasCta: "Crear una cuenta de práctica gratis",
  graciasFaq: "Leer las preguntas",
  migasInicio: "Inicio",
  migasFaq: "Preguntas",
  migasPrivacidad: "Privacidad",
  migasAria: "Migas de pan",
  pieComo: "Cómo funciona",
  pieFaq: "Preguntas",
  pieContacto: "Contacto",
  piePrivacidad: "Privacidad",
  pieApp: "Abrir la app",
  pieTryhyto: "Sitio de marketing (tryhyto.com)",
};

export function discursoDe(idioma: "en" | "es"): Record<ClaveDiscurso, string> {
  return idioma === "es" ? discursoEs : discurso;
}

export type BloqueDiscurso = { titulo: string; cuerpo: string };

export function pasosDiscurso(copia: Record<ClaveDiscurso, string> = discurso): readonly BloqueDiscurso[] {
  return [
    { titulo: copia.step1Title, cuerpo: copia.step1Body },
    { titulo: copia.step2Title, cuerpo: copia.step2Body },
    { titulo: copia.step3Title, cuerpo: copia.step3Body },
  ];
}

export function audienciasDiscurso(copia: Record<ClaveDiscurso, string> = discurso): readonly BloqueDiscurso[] {
  return [
    { titulo: copia.workersTitle, cuerpo: copia.workersBody },
    { titulo: copia.organizersTitle, cuerpo: copia.organizersBody },
  ];
}

export function preguntasDiscurso(copia: Record<ClaveDiscurso, string> = discurso): readonly BloqueDiscurso[] {
  return [
    { titulo: copia.faqCostQuestion, cuerpo: copia.faqCostAnswer },
    { titulo: copia.faqApproveQuestion, cuerpo: copia.faqApproveAnswer },
    { titulo: copia.faqRejectQuestion, cuerpo: copia.faqRejectAnswer },
    { titulo: copia.faqColonesQuestion, cuerpo: copia.faqColonesAnswer },
    { titulo: copia.faqFundsQuestion, cuerpo: copia.faqFundsAnswer },
    { titulo: copia.faqCryptoQuestion, cuerpo: copia.faqCryptoAnswer },
    { titulo: copia.faqDollarsQuestion, cuerpo: copia.faqDollarsAnswer },
  ];
}

export function confianzaDiscurso(copia: Record<ClaveDiscurso, string> = discurso): readonly BloqueDiscurso[] {
  return [
    { titulo: copia.trustApproveTitle, cuerpo: copia.trustApproveBody },
    { titulo: copia.trustAiTitle, cuerpo: copia.trustAiBody },
    { titulo: copia.trustEscrowTitle, cuerpo: copia.trustEscrowBody },
  ];
}
