import type { TipoTarea } from "@/lib/integrante/tipos";
import type { ClaseEvidencia, RespuestasFactura, RespuestasTrabajo } from "./laya";

/**
 * Laya's winning labels and Groq's missing-item count from the 8 Oct 2026
 * photo exam. No photos and no model text. The published grade is `nota`.
 */
export type CasoTecho = {
  id: string;
  tipo: TipoTarea;
  esperado: "Cumplió" | "Parcial" | "Insuficiente";
  nota: number;
  clase: ClaseEvidencia;
  tipoLectura: "trabajo" | "recibo" | "otra";
  legible: boolean;
  faltantes: number;
  trabajo: RespuestasTrabajo | null;
  factura: RespuestasFactura | null;
};

export const CASOS_TECHO: CasoTecho[] = [
  {"id":"drive-01-banner-zeek-con-mesa","tipo":"trabajo","esperado":"Cumplió","nota":77,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"armar_o_montar","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-02-banners-linkey-cursor","tipo":"trabajo","esperado":"Cumplió","nota":48,"clase":"trabajo","tipoLectura":"trabajo","legible":true,"faltantes":1,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"armar_o_montar","t6":"no_claro","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-03-botones-zeek","tipo":"trabajo","esperado":"Cumplió","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-04-stickers-otra-marca","tipo":"trabajo","esperado":"Insuficiente","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":2,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"vender_o_atender","t6":"sin_empezar","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-05-actividad-stand","tipo":"trabajo","esperado":"Cumplió","nota":66,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":true,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-06-auditorio-medio-lleno","tipo":"trabajo","esperado":"Parcial","nota":80,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":2,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":2}},
  {"id":"drive-07-expositor-sin-publico","tipo":"trabajo","esperado":"Parcial","nota":46,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":1,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"sin_empezar","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-08-set-podcast","tipo":"trabajo","esperado":"Cumplió","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_otra_cosa","v2":0,"v3":false,"v4":true,"t5":"otra_o_no_claro","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-09-comida-no-recibo","tipo":"reembolso","esperado":"Insuficiente","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":4,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"vender_o_atender","t6":"terminado","t7":false,"t8":true,"t9":true,"t10":0}},
  {"id":"drive-10-tablet-desenfocada","tipo":"trabajo","esperado":"Insuficiente","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":false,"faltantes":2,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"a_medias","t7":true,"t8":true,"t9":true,"t10":1}},
  {"id":"drive-11-muro-fotos-vacio","tipo":"trabajo","esperado":"Insuficiente","nota":49,"clase":"trabajo","tipoLectura":"trabajo","legible":true,"faltantes":2,"factura":null,"trabajo":{"lugar":"espacio_abierto","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-12-tablet-qr-no-lista","tipo":"trabajo","esperado":"Insuficiente","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":2,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"vender_o_atender","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-13-bienvenida-voluntarios","tipo":"trabajo","esperado":"Cumplió","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"a_medias","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-14-pantalla-patrocinadores","tipo":"trabajo","esperado":"Insuficiente","nota":43,"clase":"factura","tipoLectura":"trabajo","legible":true,"faltantes":1,"trabajo":null,"factura":{"f1":"coincide_con_lo_pedido","f2":false,"f3":false,"f4":1,"g1":"impresion_o_papeleria","g2":false,"g3":true,"g4":true,"g5":0}},
  {"id":"drive-15-stand-dos-banners","tipo":"trabajo","esperado":"Cumplió","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"armar_o_montar","t6":"terminado","t7":true,"t8":true,"t9":true,"t10":1}},
  {"id":"drive-16-banners-tapados","tipo":"trabajo","esperado":"Parcial","nota":68,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":3,"factura":null,"trabajo":{"lugar":"espacio_abierto","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"armar_o_montar","t6":"terminado","t7":true,"t8":true,"t9":true,"t10":1}},
  {"id":"drive-17-stand-recortado","tipo":"trabajo","esperado":"Parcial","nota":36,"clase":"factura","tipoLectura":"trabajo","legible":true,"faltantes":3,"trabajo":null,"factura":{"f1":"coincide_con_lo_pedido","f2":false,"f3":false,"f4":1,"g1":"materiales","g2":false,"g3":false,"g4":false,"g5":1}},
  {"id":"drive-18-marimba-otra-cosa","tipo":"trabajo","esperado":"Insuficiente","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":2,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"armar_o_montar","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-19-muro-fotos-a-medias","tipo":"trabajo","esperado":"Parcial","nota":77,"clase":"trabajo","tipoLectura":"trabajo","legible":true,"faltantes":2,"factura":null,"trabajo":{"lugar":"pared_o_superficie","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-20-foto-pantalla-camara","tipo":"trabajo","esperado":"Parcial","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"pared_o_superficie","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"terminado","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-21-foto-grupal-banners","tipo":"trabajo","esperado":"Cumplió","nota":49,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"pared_o_superficie","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"sin_empezar","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-22-charla-con-publico","tipo":"trabajo","esperado":"Cumplió","nota":76,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-23-solo-diapositiva","tipo":"trabajo","esperado":"Parcial","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":2,"factura":null,"trabajo":{"lugar":"espacio_abierto","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"a_medias","t7":false,"t8":true,"t9":true,"t10":1}},
  {"id":"drive-24-pizzas-no-recibo","tipo":"reembolso","esperado":"Insuficiente","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":4,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"vender_o_atender","t6":"sin_empezar","t7":false,"t8":true,"t9":true,"t10":1}},
  {"id":"drive-25-snacks-en-caja","tipo":"trabajo","esperado":"Parcial","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":false,"faltantes":3,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"a_medias","t7":false,"t8":true,"t9":true,"t10":1}},
  {"id":"drive-26-pantalla-no-banner","tipo":"trabajo","esperado":"Parcial","nota":44,"clase":"trabajo","tipoLectura":"trabajo","legible":true,"faltantes":1,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-27-stickers-tellus","tipo":"trabajo","esperado":"Cumplió","nota":39,"clase":"trabajo","tipoLectura":"trabajo","legible":false,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"vender_o_atender","t6":"a_medias","t7":false,"t8":false,"t9":true,"t10":1}},
  {"id":"drive-28-letrero-entrada-cerca","tipo":"trabajo","esperado":"Cumplió","nota":77,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"espacio_abierto","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-29-letrero-entrada-lejos","tipo":"trabajo","esperado":"Cumplió","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":1,"factura":null,"trabajo":{"lugar":"espacio_abierto","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"terminado","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-30-entrada-sin-letrero","tipo":"trabajo","esperado":"Insuficiente","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":1,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":false,"t9":true,"t10":1}},
  {"id":"drive-31-banner-sala-vacia","tipo":"trabajo","esperado":"Cumplió","nota":73,"clase":"factura","tipoLectura":"trabajo","legible":true,"faltantes":0,"trabajo":null,"factura":{"f1":"coincide_con_lo_pedido","f2":false,"f3":false,"f4":1,"g1":"materiales","g2":true,"g3":true,"g4":true,"g5":2}},
  {"id":"drive-32-muro-fotos-lleno","tipo":"trabajo","esperado":"Cumplió","nota":68,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"pared_o_superficie","v1":"es_lo_pedido","v2":1,"v3":true,"v4":true,"t5":"transportar","t6":"terminado","t7":true,"t8":true,"t9":true,"t10":1}},
  {"id":"drive-33-coworking-luz-calida","tipo":"trabajo","esperado":"Cumplió","nota":41,"clase":"factura","tipoLectura":"trabajo","legible":true,"faltantes":0,"trabajo":null,"factura":{"f1":"coincide_con_lo_pedido","f2":false,"f3":false,"f4":1,"g1":"materiales","g2":false,"g3":false,"g4":false,"g5":2}},
  {"id":"drive-34-planta-cafe-otra-cosa","tipo":"trabajo","esperado":"Insuficiente","nota":34,"clase":"trabajo","tipoLectura":"otra","legible":true,"faltantes":3,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"otra_o_no_claro","t6":"no_claro","t7":false,"t8":false,"t9":false,"t10":0}},
  {"id":"drive-35-stickers-mesa-oscura","tipo":"trabajo","esperado":"Cumplió","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"vender_o_atender","t6":"a_medias","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-36-taza-con-logo","tipo":"trabajo","esperado":"Cumplió","nota":0,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":1,"factura":null,"trabajo":{"lugar":"no_claro","v1":"es_otra_cosa","v2":1,"v3":false,"v4":false,"t5":"otra_o_no_claro","t6":"sin_empezar","t7":false,"t8":false,"t9":false,"t10":1}},
  {"id":"drive-37-bebida-oscura-borrosa","tipo":"trabajo","esperado":"Parcial","nota":49,"clase":"trabajo","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-38-bebidas-con-logo","tipo":"trabajo","esperado":"Cumplió","nota":66,"clase":"otra","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"no_claro","v1":"no_se_puede_saber","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":false,"t8":true,"t9":false,"t10":1}},
  {"id":"drive-39-pasteles-no-recibo","tipo":"reembolso","esperado":"Insuficiente","nota":40,"clase":"factura","tipoLectura":"trabajo","legible":true,"faltantes":4,"trabajo":null,"factura":{"f1":"coincide_con_lo_pedido","f2":true,"f3":true,"f4":1,"g1":"comida_o_bebida","g2":true,"g3":false,"g4":true,"g5":1}},
  {"id":"drive-40-foto-grupal-cafe","tipo":"trabajo","esperado":"Cumplió","nota":48,"clase":"trabajo","tipoLectura":"trabajo","legible":true,"faltantes":0,"factura":null,"trabajo":{"lugar":"stand_o_mesa","v1":"es_otra_cosa","v2":1,"v3":true,"v4":true,"t5":"pintar","t6":"terminado","t7":true,"t8":true,"t9":true,"t10":1}},
];
