import type { TareaAdmin } from "./tipos";

export const PROYECTO_EJEMPLO = "ZEEK";

export function tareasEjemploAdmin(): TareaAdmin[] {
  return [
    {
      id: "stand",
      titulo: "Montar el stand",
      tipo: "trabajo",
      monto: "20",
      tope: null,
      condicion: "Banner visible y mesa armada",
      miembroId: "voluntario-1",
      miembro: "Voluntario 1",
      estado: "en revisión",
      veredicto: "cumplió",
      frase: "Mesa armada, banner de ZEEK de frente y el salón visible.",
      montoRevisado: null,
      fecha: null,
      hashPago: null,
      credencialUrl: null,
    },
    {
      id: "registro",
      titulo: "Registro de asistentes",
      tipo: "trabajo",
      monto: "20",
      tope: null,
      condicion: "Lista de quienes llegaron al evento",
      miembroId: "voluntario-2",
      miembro: "Voluntario 2",
      estado: "en revisión",
      veredicto: "parcial",
      frase: "Lista a medias: se ven algunas firmas y el fondo del salón no entra en la foto.",
      montoRevisado: null,
      fecha: null,
      hashPago: null,
      credencialUrl: null,
    },
    {
      id: "bienvenida",
      titulo: "Mesa de bienvenida",
      tipo: "trabajo",
      monto: "20",
      tope: null,
      condicion: "Mesa armada en la entrada",
      miembroId: "voluntario-3",
      miembro: "Voluntario 3",
      estado: "pendiente",
      veredicto: null,
      frase: null,
      montoRevisado: null,
      fecha: null,
      hashPago: null,
      credencialUrl: null,
    },
    {
      id: "comida",
      titulo: "Comida del equipo",
      tipo: "reembolso",
      monto: "15",
      tope: "15",
      condicion: "Foto del comprobante de la comida",
      miembroId: "voluntario-1",
      miembro: "Voluntario 1",
      estado: "en revisión",
      veredicto: "cumplió",
      frase: "Comprobante de la comida del equipo, con monto y fecha visibles.",
      montoRevisado: "12.40",
      fecha: "2026-09-27",
      hashPago: null,
      credencialUrl: null,
    },
  ];
}
