import type { TareaAdmin } from "./tipos";

export const PROYECTO_EJEMPLO = "ZEEK";

export function tareasEjemploAdmin(): TareaAdmin[] {
  return [
    {
      id: "stand",
      titulo: "Set up the booth",
      tipo: "trabajo",
      monto: "20",
      tope: null,
      condicion: "Banner visible and the table set up",
      miembroId: "voluntario-1",
      miembro: "Volunteer 1",
      estado: "en revisión",
      veredicto: "cumplió",
      frase: "Table set up, ZEEK banner facing forward, and the room is visible.",
      origen: "guion",
      codigo: null,
      montoRevisado: null,
      montoConfirmado: null,
      fecha: null,
      hashPago: null,
      credencialUrl: null,
    },
    {
      id: "registro",
      titulo: "Check-in list",
      tipo: "trabajo",
      monto: "20",
      tope: null,
      condicion: "List of people who arrived",
      miembroId: "voluntario-2",
      miembro: "Volunteer 2",
      estado: "en revisión",
      veredicto: "parcial",
      frase: "The list is incomplete: a few signatures show, and the back of the room is out of frame.",
      origen: "guion",
      codigo: null,
      montoRevisado: null,
      montoConfirmado: null,
      fecha: null,
      hashPago: null,
      credencialUrl: null,
    },
    {
      id: "bienvenida",
      titulo: "Welcome table",
      tipo: "trabajo",
      monto: "20",
      tope: null,
      condicion: "Table set up at the entrance",
      miembroId: "voluntario-3",
      miembro: "Volunteer 3",
      estado: "pendiente",
      veredicto: null,
      frase: null,
      origen: null,
      codigo: null,
      montoRevisado: null,
      montoConfirmado: null,
      fecha: null,
      hashPago: null,
      credencialUrl: null,
    },
    {
      id: "comida",
      titulo: "Team meal",
      tipo: "reembolso",
      monto: "15",
      tope: "15",
      condicion: "Photo of the meal receipt",
      miembroId: "voluntario-1",
      miembro: "Volunteer 1",
      estado: "en revisión",
      veredicto: "cumplió",
      frase: "Team meal receipt, with the amount and date visible.",
      origen: "guion",
      codigo: null,
      montoRevisado: "12.40",
      montoConfirmado: null,
      fecha: "2026-09-27",
      hashPago: null,
      credencialUrl: null,
    },
  ];
}
