import type { Tarea } from "./tipos";

const PROYECTO = "zeek";

const TAREAS: Tarea[] = [
  {
    id: "stand",
    proyectoId: PROYECTO,
    titulo: "Set up the booth",
    tipo: "trabajo",
    monto: "20",
    tope: null,
    condicion: "Banner visible and the table set up",
    miembroId: "voluntario-1",
    walletCobro: "",
    estado: "pendiente",
    prioridad: "normal",
    dificultad: null,
  },
  {
    id: "registro",
    proyectoId: PROYECTO,
    titulo: "Check-in list",
    tipo: "trabajo",
    monto: "20",
    tope: null,
    condicion: "List of people who arrived",
    miembroId: "voluntario-2",
    walletCobro: "",
    estado: "pendiente",
    prioridad: "normal",
    dificultad: null,
  },
  {
    id: "bienvenida",
    proyectoId: PROYECTO,
    titulo: "Welcome table",
    tipo: "trabajo",
    monto: "20",
    tope: null,
    condicion: "Table set up at the entrance",
    miembroId: "voluntario-3",
    walletCobro: "",
    estado: "pendiente",
    prioridad: "normal",
    dificultad: null,
  },
  {
    id: "comida",
    proyectoId: PROYECTO,
    titulo: "Team meal",
    tipo: "reembolso",
    monto: "15",
    tope: "15",
    condicion: "Photo of the meal receipt",
    miembroId: "voluntario-1",
    walletCobro: "",
    estado: "pendiente",
    prioridad: "normal",
    dificultad: null,
  },
  {
    id: "pulsera",
    proyectoId: PROYECTO,
    titulo: "Wristband check",
    tipo: "trabajo",
    monto: "12",
    tope: null,
    condicion: "The wristband is in the frame; The table is visible; Your face stays out",
    miembroId: "demo-voluntario",
    walletCobro: "",
    estado: "pendiente",
    prioridad: "high",
    dificultad: null,
    venceEn: "2026-12-31T22:00:00.000Z",
    rechazada: true,
    intentos: 2,
    organizador: { nombre: "Organizer" },
    etapa: "rechazada",
    rechazo: {
      nota: "The wristband is cropped out.",
      fallidos: ["0"],
      en: "2026-10-05T21:00:00.000Z",
      origen: "organizador",
    },
    requisitos: [
      { id: "0", texto: "The wristband is in the frame", cumple: false, motivo: "The wristband is cropped out." },
      { id: "1", texto: "The table is visible", cumple: true, motivo: null },
      { id: "2", texto: "Your face stays out", cumple: true, motivo: null },
    ],
  },
  {
    id: "cierre",
    proyectoId: PROYECTO,
    titulo: "Close the booth",
    tipo: "trabajo",
    monto: "18",
    tope: null,
    condicion: "The booth is packed",
    miembroId: "demo-voluntario",
    walletCobro: "",
    estado: "pagado",
    prioridad: "normal",
    dificultad: null,
    intentos: 1,
    organizador: { nombre: "Organizer" },
    etapa: "aprobada",
    ["hashPago"]: "ab".repeat(32),
  },
];

export function tareasEjemplo(): Tarea[] {
  return TAREAS.map((tarea) => ({ ...tarea }));
}
